### ISSUE TITLE
Feature request: testcard when no input

### ISSUE THREAD

**Issue by phillipseamore** [CESNET/UltraGrid#1]
When started with capture device and no frames are received UltraGrid should send a testcard with test sound (i.e. on startup and also if input is lost).

It would also be great if the testcard generator could burn-in timecode and have configurable text for identification of the signal.

**Comment by MartinPulec** [comment]
Hi Phillip,
I've added some beta version of you have asked for. Unfortunately, I do not have enough time to do more right now and I am not sure, whether/when it will land in the main branch - basically, we consider rather steady (user-suplied) image as a placeholder, however, bars with burnt-in timecode would look nice as well.

The code itself is in the branch *decklink-splash*. It does not support audio (yet) and must be enabled manually by adding *:always_signal" option.

To the last request, text annotation, I think you can do it right now using *text* capture filter (see [here](https://www.sitola.cz/igrid/index.php/Capture_filters#text)), you just need to have MagickWand (including headers) to compile it.

Feel free to let me know what you think.

Regards,
Martin

**Comment by MartinPulec** [comment]
This can be implemented as a virtual capture (aka video switcher) that sends a primary source and when on input, it switches to a secondary source (or generates autonomously the signal). Maybe this can be even added to the video switcher. Closing for now, reopen in case of interest.
