### ISSUE TITLE
NDI only Embeds 1 audio track! Bad Audio if more

### ISSUE THREAD

**Issue by thpryrchn** [CESNET/UltraGrid#101]
If I receive more than 1 audio channel, the audio is bad. 2 channels, it sounds like it is playing half speed in real time.
`uv -d ndi -r embedded` 
So Currently, UltraGrid only creates NDI streams with 1 audio channel.

This is on both mac & Ubuntu 20.04

Both OBS, and NDI Monitor play the NDI stream from Ultragrid the same. I thought it was completely broke, until I tried it with just 1 audio channel, and it was fine.

**Comment by MartinPulec** [comment]
Hi, thanks, I think it may be now fixed with commit 87d3d370.

**Comment by thpryrchn** [comment]
It works!! That was quick!!!!
