### ISSUE TITLE
GUI: No embed option for audio when using NDI, and NDI doesn't put source in command line...

### ISSUE THREAD

**Issue by thpryrchn** [CESNET/UltraGrid#102]
With the GUI on both Mac & Linux, When there is more than one NDI source on the network, they all show up in the Video source, but no matter which one is selected, it only uses `-t ndi`. So it needs to do either a `-t ndi:name="IMAC-PRO.LOCAL (NDI Signal Generator)"` or use the URL of the IP and port that it sees.

There is no embedded option on the audio section when selecting a NDI source...

**Comment by MartinPulec** [comment]
Thanks, there was problem in passing the parameters between UltraGrid and the GUI, it may be fixed now. Also the audio selection should work for NDI.

**Comment by thpryrchn** [comment]
Works now!
Thanks!!
