### ISSUE TITLE
Decklink `detect-format` doesn't scan HDMI

### ISSUE THREAD

**Issue by thpryrchn** [CESNET/UltraGrid#103]
The `-t decklink:detect-format:device=0` doesn't work with HDMI as an input. It does with SDI... This is on a "UltraStudio Mini Recorder". It does work if I do `-t decklink:detect-format:connection=HDMI:device=0`, or just `-t decklink:connection=HDMI`

**Comment by MartinPulec** [comment]
Hi, this is quite expected behavior - that option scans for input format but not for input connection (which is SDI by default).

**Comment by thpryrchn** [comment]
I was able to modify the code so it works easily from the GUI to autodetect from HDMI, or any detected connection to a Decklink card...

https://github.com/CESNET/UltraGrid/pull/104
