### ISSUE TITLE
GUI: Decklink no Embedded audio for playback....

### ISSUE THREAD

**Issue by thpryrchn** [CESNET/UltraGrid#106]
On my DeckLink Mini Monitor 4K, I have no Embedded audio for playback. I attached my `uv --capabilities > cap.txt`

It does give me the "Audio-only output through DeckLink device" option, but that doesn't work when the Decklink is used for Video Playback.

It does work, if I edit the command line from `-r decklink` to `-r embedded`

[cap.txt](https://github.com/CESNET/UltraGrid/files/5585259/cap.txt)

If I comment out this part, I get embedded all the time. But this isn't the proper way to do things.
```
std::vector<SettingItem> getAudioPlayback(AvailableSettings *availSettings){
    const std::string optStr = "audio.playback";
    std::vector<SettingItem> res;

    SettingItem defaultItem;
    defaultItem.name = "None";
    defaultItem.opts.push_back({optStr, ""});
    res.push_back(std::move(defaultItem));

    for(const auto &i : availSettings->getDevices(AUDIO_PLAYBACK)){
        SettingItem item;
        item.name = i.name;
        item.opts.push_back({optStr, i.type});
        // for(const auto &sdi : sdiAudio){
        //     if(std::strcmp(sdi, i.type.c_str()) == 0){
        //         item.conditions = getSdiCond("video.display");
        //         break;
        //     }
        // }
        res.push_back(std::move(item));
    }

    return res;
}
```

**Comment by mpiatka** [comment]
Hi,
thanks for reporting. I pushed a dirty fix that should solve the problem for now.
