### ISSUE TITLE
GUI: Save Settings open's a "Open Dialog"

### ISSUE THREAD

**Issue by thpryrchn** [CESNET/UltraGrid#107]
The Save settings does not allow you to save a file (a Save Dialog) it instead opens a Open Dialog.

If I create a blank .json file, and select it, it will save the settings over it.

This is the same on Mac & Ubuntu

**Comment by mpiatka** [comment]
Hi,
thanks for reporting. The QFileDialog that was used should have allowed to save to a new file, however I agree that it was somewhat confusing.

I replaced it with QFileDialog::getSaveFileName and that should be a bit more intuitive. Let me know if it works better.

**Comment by thpryrchn** [comment]
Perfect!
