### ISSUE TITLE
GUI: When NDI source is selected, the modes from Decklink are shown.

### ISSUE THREAD

**Issue by thpryrchn** [CESNET/UltraGrid#108]
The Modes don't do anything, so it isn't a big problem

**Comment by MartinPulec** [comment]
Hi @thpryrchn, would you be able to generate the capabilities output (`uv --capabilities`) and post it here? I've tried to reproduce it but it doesn't occur in my setup. So it may be condition-dependent.

Thanks, Martin

**Comment by thpryrchn** [comment]
You know, it may have been one of me hacked versions.  I made sure I had the latest compile on it, and now it doesn't show nodes when NDI is selected.
