### ISSUE TITLE
GUI: When using embedded playback & preview, sound doesn't work...

### ISSUE THREAD

**Issue by thpryrchn** [CESNET/UltraGrid#109]
The Multiplier should use the first option for the embedded output. 

This fails for both NDI, and Decklink.

Works perfectly when preview is disabled.

**Comment by MartinPulec** [comment]
I've pushed that simple update. If you could test it would be nice (I didn't have time to).

**Comment by thpryrchn** [comment]
Sorry it took so long... I upgraded my macOS, and had trouble geting it to compile.... But it is good now...

The commit you did fixed it for both NDI and Decklink!
