### ISSUE TITLE
Stream doesn't stop when quitting receiver

### ISSUE THREAD

**Issue by llamafilm** [CESNET/UltraGrid#115]
My receiver is behind a NAT, so I setup UDP hole punching as described in the [Wiki](https://github.com/CESNET/UltraGrid/wiki/NAT-traversal#udp-hole-punching).  This works nicely, but there is a problem.  When I quit the receiver with Ctrl+C, the stream does not stop.  The data is still flowing, it just goes to `kernel_task` instead of `uv`.  (You can see it with `iftop` on linux.)
Is this a bug or is there some other way to stop the stream?  I would like to set it up so that the stream can be turned on/off by the client side.  I am sending from Linux to macOS.

**Comment by erichorwitz** [comment]
Elliot

Have you checked out the control port API?

https://github.com/CESNET/UltraGrid/wiki/Control-port-API

Eric-

**Comment by llamafilm** [comment]
I had not seen that, thanks.  This sounds useful.

**Comment by MartinPulec** [comment]
Hi Elliott, this looks like a bug. What are the actual UltraGrid parameters? Also if you'd able to generate a backtrace after "exited" (eg. from core dump when forcibly closed), it would be superb.

**Comment by alatteri** [comment]
> When I quit the receiver with Ctrl+C, the stream does not stop. The data is still flowing

Wouldn't that just be the nature of UDP?  The sender just keeps spitting data out, and technically it is still coming into the endpoint interface?

Maybe this is unique to the NAT UDP Hole Punch function, I never used that.

**Comment by MartinPulec** [comment]
> Wouldn't that just be the nature of UDP? The sender just keeps spitting data out, and technically it is still coming into the endpoint interface?

Ok ok, I may have misunderstood the question then - I thought that UltraGrid doesn't stop, not that data is still flowing. If this is the thing, then yes, you are correct @alatteri, that is expected behavior and as @erichorwitz suggested, the sender needs to be paused/stopped. I think that after some time, the NAT forgets the translation if there is no traffic from inside to out, but it is not deterministic. And yet still it will flow to the external interface of the NAT.

**Comment by llamafilm** [comment]
UltraGrid process does stop. I understand the sender will keep going. But it seems weird that the receiving computer keeps receiving the data because I thought the NAT translation would be broken as soon as the receiver process stops. Maybe this is normal UDP behavior as you say, but I was surprised by it.

**Comment by MartinPulec** [comment]
> UltraGrid process does stop. I understand the sender will keep going. But it seems weird that the receiving computer keeps receiving the data because I thought the NAT translation would be broken as soon as the receiver process stops. Maybe this is normal UDP behavior as you say, but I was surprised by it.

I see, well, this perhaps depends on NAT implementation - I assume that both could be possible, keeping alive only when there is some IN->OUT traffic or inhibiting also by OUT->IN traffic. But I cannot say for sure.

UltraGrid itself, using NAT-PMP or PCP, uses a 30 minutes' interval to renew mapping by default - it can, however, be configured.
