### ISSUE TITLE
NVENC_HEVC 10bit....  YUV444 or RGB10?

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#116]
Hi in looking at NVENC_HEVC SDK for other things, I noticed this.

> The input surface format needs be set to NV_ENC_BUFFER_FORMAT_YUV420_10BIT OR NV_ENC_BUFFER_FORMAT_ABGR10 or NV_ENC_BUFFER_FORMAT_ARGB10 or NV_ENC_BUFFER_FORMAT_YUV444_10BIT, depending upon nature of input.

So I am wondering, in the scenario of ingesting Decklink R10k, would UG be using NVENC YUV444_10BIT or ARGB10?

Thanks,
Alan

**Comment by MartinPulec** [comment]
Well, UltraGrid cannot use any 10-bit RGB pixel format anyway because FFmpeg doesn't provide it for NVENC.
