### ISSUE TITLE
single thread decoding when input stream is SVT-HEVC

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#121]
Hello,

I've been testing SVT-HEVC compressions.  The encode performance is great, it can utilize a higher thread count than x265.  But I am noticing that when decoding this stream, UG seems to be using basically a single core, resulting it basically an unusable stream.   See the attached screenshots.  Utilizing a AppImage from about 2 weeks ago..

![IMG_0940](https://user-images.githubusercontent.com/625982/102288272-07924900-3ef1-11eb-98f6-eeca1343e8bd.jpeg)
![IMG_0939](https://user-images.githubusercontent.com/625982/102288274-082adf80-3ef1-11eb-8df6-89a583fc46cc.jpeg)
![IMG_0938](https://user-images.githubusercontent.com/625982/102288275-082adf80-3ef1-11eb-9ba4-bf5c356fce30.jpeg)

**Comment by llamafilm** [comment]
I'm seeing the same issue with HEVC_NVENC.  A 20Mbps stream nearly maxes out one core of Intel i7-6950x at 3GHz.

**Comment by MartinPulec** [comment]
@llamafilm It is because FFmpeg sets only one slice for NVENC. UltraGrid AppImage FFmpeg build overrides that (commit e9aab89) for H.264. But the symmetric change for HEVC didn't have the positive impact on decoding performance when I've tested few months ago. Don't know why - if the situation changes (SW updated or newer SIP?) it may be enabled as well. But at the time of testing, the impact of the change was actually negative - unfortunately I am not an expert to tell why.

**Comment by MartinPulec** [comment]
@alatteri I've pushed a commit that enables multiple slices for SVT HEVC and AV1 (a7c6f31b). However, at least from my first tests, it didn't look to make a significant change (for HEVC, didn't test AV1). If you had another idea which option may be used, I'd be glad to hear. I am afraid that this are the most relevant options.

Another possibility is that this is not the matter of the encoder but actually the FFmpeg HEVC decoder doesn't parallelize well - that would also explain why neither NVENC with multiple slices doesn't improve decoding performance. I've found [this](https://github.com/FFmpeg/FFmpeg/blob/c2424b1f35a1c6c06f1f9fe5f77a7157ed84e1cd/libavcodec/hevcdec.c#L912-L916) in FFmpeg sources. So in my opinion this could be it. If so, I think that only option is to use HW accelerations (or HW accelerated decoders, like cuvid).

**Comment by alatteri** [comment]
Hi Martin... Yes it is strange.  With x265 encoding, the decoder does seem to be multi-threaded.  I'll try to test this weekend.

Thanks.

**Comment by MartinPulec** [comment]
Yep, you are right! I've realized that as well. Strange then, I'll try to look at that as well. Another possibility is that the parallelization there is at a different level, not slice-based. But just guessing.

**Comment by llamafilm** [comment]
There are lots of references to sliceMode in the Nvidia SDK.  Maybe it's turned off by default.

>uint32_t sliceMode;                                             
/** This parameter in conjunction with sliceModeData specifies the way in which the picture is divided into slices
sliceMode = 0 CTU based slices, sliceMode = 1 Byte based slices, sliceMode = 2 CTU row based slices, sliceMode = 3, numSlices in Picture
When sliceMode == 0 and sliceModeData == 0 whole picture will be coded with one slice */

>uint32_t sliceModeData;                                         
/**< [in]: Specifies the parameter needed for sliceMode. For:
sliceMode = 0, sliceModeData specifies # of CTUs in each slice (except last slice)
sliceMode = 1, sliceModeData specifies maximum # of bytes in each slice (except last slice)
sliceMode = 2, sliceModeData specifies # of CTU rows in each slice (except last slice)
sliceMode = 3, sliceModeData specifies number of slices in the picture. Driver will divide picture into slices optimally */

**Comment by MartinPulec** [comment]
> There are lots of references to sliceMode in the Nvidia SDK. Maybe it's turned off by default.

Yes, it is. That is what fixes the above mentioned commit for H.264. It is true for HEVC as well, but enabling that there doesn't have a positive impact on decoding performance.

**Comment by MartinPulec** [comment]
Not sure if it helps but I've added a possibility to use a frame-level parallelism - `--param lavd-thread-count <thread_count>F` (0 also possible as a thread count). By default, frame parallelism is never used in UltraGrid (latency).

**Comment by MartinPulec** [comment]
I believe this is already fixed (#241).
