### ISSUE TITLE
Feature REQ: GUI: Encoder selection / Auto Hardware Compression option

### ISSUE THREAD

**Issue by thpryrchn** [CESNET/UltraGrid#126]
I just discovered `-c libavcodec:encoder=hevc_videotoolbox:bitrate=8m` works wonders on a mac! Where before the x265 default was garbage.

If you click on the Advanced tab for the GUI, it should list all the codec encoders for video.

OR maybe when you select Compression, there would be a 2nd dropdown for the encoder. with Default, and whatever `uv -c libavcodec:help` shows on that particular system.

In the non advanced mode, it would be cook if H264/H265 had a "Try hardware encoding" setting. That Auto mode would first try Hardware encoding, and if that fails, fallback to x264/x265

Note: For anyone out there who wants to save a profile with custom commands, just put them in the **Destination** field. 
So currently for me to do a custom Video compression, leave the **Compression** field set to None. 
Currently I have this in mine: `-c libavcodec:encoder=hevc_videotoolbox:bitrate=8m 192.168.1.147`. And save the settings. This way, I can easily select different sources, and hit start. As the "Edit arguments" locks all other controls, and the edits disappear once you uncheck it.

Being able to put options in the **Destination** field may be considered a bug, But I consider it a feature :)

**Comment by mpiatka** [comment]
In the current nightly build the GUI now parses all available codecs and their encoders. The encoder can be selected in the UltraGrid -> Settings -> Video compress menu.
