### ISSUE TITLE
when ultragrid with spout or syphon server - it is only possible with open gl-windows

### ISSUE THREAD

**Issue by maybites** [CESNET/UltraGrid#134]
Hi

currently you need to use

uv -d gl:syphon=<SyphonServer>

uv -d gl:spout=<SpoutServer>

to stream to spout/syphon - with the drawback of opening a window.

I wonder if it would be possible to implement syphon/spout like with NDI without the need to open a window.

cheers

martin

**Comment by MartinPulec** [comment]
Hi,

both grab GL output so it is quite related. There is an option ':hide-window', isn't it sufficient for that purpose? I don't think it would be reasonable to make those as standalone modules, maybe just an alias (but not sure about it now).

Martin

**Comment by maybites** [comment]
Hi

I didn't know the option ':hide-window'. It might do the trick. I will get back to you..

**Comment by maybites** [comment]
thats perfectly sufficient and works fine for me. Thank you for the quick reply.
