### ISSUE TITLE
drop policy

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#138]
Hi guys,

Can you explain what the new drop policy option does.  I'm not clear on how it affects operation.

Thanks.

**Comment by MartinPulec** [comment]
Hi Alan, don't bother with that much. It doesn't change the default behavior and it is not a new option - it is there already some time (although it has not been possible to set it actually). It just controls what to do if frame cannot be displayed without blocking. But I'd consider this option for rather debug only than user-tunable (like most of the `--params` options).

**Comment by alatteri** [comment]
Thank you for the clarification.

**Comment by MartinPulec** [comment]
I could imagine that setting to blocking may help in a network which has some error corrections on lower layers, perhaps cellular or wireless (i. e. with high traffic jitter, but obviously limited losses). But I am not aware to be used since change of default behavior (blocking->non-blocking).
