### ISSUE TITLE
OSX continuous alt build 10.11+ videotoolbox decode

### ISSUE THREAD

**Issue by erichorwitz** [CESNET/UltraGrid#145]
It appears that there is support for Videotoolbox encoding but not decoding. I downloaded the dmg from the releases. Is this an issue with the build or am I missing a library? Running on a Mac Pro 6,1 on os x 10.13.6

**Comment by MartinPulec** [comment]
Hi Eric,

correct. This is because the encoder is standalone but decoder is not (an accelerator only). The support would need to be added for this.

**Comment by mpiatka** [comment]
Hi,

yesterday I pushed code enabling videotoolbox decoding into the master branch. It should be already available on the continuous builds. To use the hw. acceleration `--param use-hw-accel` needs to be specified.
