### ISSUE TITLE
TTL when attempting Multicast

### ISSUE THREAD

**Issue by TheSashmo** [CESNET/UltraGrid#146]
I can see in multiple locations calling for code for TTL, but there is no exact description of how to apply that in the command line argument to support a TTL anything other than the default of 255.

Any suggestions here, did I miss something?

**Comment by MartinPulec** [comment]
Hi @TheSashmo, it is really currently hard-coded to 255, as you can see [here](https://github.com/CESNET/UltraGrid/blob/d8d1c7a03b32bce2ef9b1b12e3ab648b4e697524/src/video_rxtx/rtp.cpp#L294). The thing is that it that it usually doesn't need to be changed. But I agree that it may have some significance for multicast.

**Comment by TheSashmo** [comment]
Wonderful. I see that thanks.

**Comment by MartinPulec** [comment]
Just FYI, I've added `-T/--ttl` parameter which now controls both multicast and unicast TTL. The default UG behavior is slightly changed in a way, that 255 is now not set explicitly - the defaults are now used (which is AFAIK 1 for IPv4 multicast and route default for IPv6 mcast).

**Comment by TheSashmo** [comment]
Great and thanks.
