### ISSUE TITLE
Ctrl+c hangs at output

### ISSUE THREAD

**Issue by TheSashmo** [CESNET/UltraGrid#149]
Here is how to reproduce:

Ubuntu 20 Desktop

`uv -t testcard:1920:1080:60:UYVY -s testcard:ebu -c libavcodec:encoder=libx264:bitrate=8000k --audio-codec=AAC:sample_rate=48000:bitrate=128k --audio-capture-format channels=8 127.0.0.1 -l unlimited -m 1316 -P 10000`

`uv -d decklink:device=0 -r alsa:dmix:CARD=PCH,DEV=0 127.0.0.1 -P 10000`

Ctrl+c freezes output, dosnt drop back to CLI and kill option is needed to close the application.

**Comment by MartinPulec** [comment]
Hi, thanks, would it be possible to provide more information?

1. which of those 2 processes actually freezes
2. what is the UltraGrid version
3. context (end of) terminal output of the freezed process

Also if the reproducibility is satisfactory - is it possible to reduce the use case to a minimal, yet "working", example?

Thanks a lot!
Martin

**Comment by TheSashmo** [comment]
Sorry for not being clear enough.  It was a late night.

On the decoder side the output is stuck.  The encoder can close properly without issue.  

Update:  The issue only happens when there are more than 2 audio channels.  If I change the encode to 2, channels ctrl+c works just fine to stop the decoder.  Once I go back to more than 2 channels, thats when the issue easily reproducible where the decoder can not close.

Ctrl+\ does nothing.  Ctrl+shift+\ does the sigquit.  Yes that works.

**Comment by MartinPulec** [comment]
Ok, I've find out that there is a problem, when the count of received channels exceeds maximal number of channels provided by ALSA playback. It is fixed now - the fix is already present in _continuous_ build, will arrive later to _1.6_.
