### ISSUE TITLE
Multi-channel CoreAudio output

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#15]
When receiving audio via CoreAudio, it seems only channels 0&1 are being output.  I know the sending commanding and signal is good, if I output using Decklink on another linux machine, I get all channels.

Sender is Debian/Decklink
Receiver is MacBookPro 10.14

`uv -t decklink -c libavcodec:codec=H.264:bitrate=20M -s embedded --audio-capture-format channels=8 --audio-codec OPUS:bitrate=256000`

`./uv -d sdl -r coreaudio`

**Comment by MartinPulec** [comment]
Can you please try to set the layout manually as pictured [here](https://stackoverflow.com/questions/16557371/how-to-set-speaker-configuration-programatically-using-core-audio-api-on-mac-os) and check if it helps? (It is under "Audio Devices" -> "Configure Speakers..."). If so, it may be possible to control it programatically as well.

Thanks,
Martin

**Comment by alatteri** [comment]
Hi Martin,

This was indeed the issue.  More specifically, I was testing on a laptop, I thought CoreAudio would do an auto down mix from 8 channels to stereo.  Quicktime Player, and I believe VLC, does this with .MOVs.  I connected my laptop to a HDMI tv which does do a proper down mix, and I was able to hear the output of all channels.

Thanks again.
Alan
