### ISSUE TITLE
Opus audio channels crash

### ISSUE THREAD

**Issue by TheSashmo** [CESNET/UltraGrid#151]
Here is an example of encoding only sending to SDP so that I can send to web.

`uv -t decklink:connection=SDI:device=2:mode=Hp59:codec=UYVY -c libavcodec:encoder=libx264:bitrate=9000k:preset=faster:subsampling=420 -s embedded --audio-codec=OPUS:sample_rate=48000:bitrate=128k --audio-capture-format channels=2 -l unlimited -m 1316 -P 18104 --protocol sdp 127.0.0.1
UltraGrid 1.6+ (tags/continuous rev 797d4a07 built Feb 23 2021 20:15:58)

Display device   : none
Capture device   : decklink
Audio capture    : embedded
Audio playback   : none
MTU              : 1316 B
Video compression: libavcodec:encoder=libx264:bitrate=9000k:preset=faster:subsampling=420
Audio codec      : OPUS
Network protocol : RTP standard (SDP version)
Audio FEC        : none
Video FEC        : none

[lavcd aud.] Using audio encoder: libopus
Created new RTP session with SSRC 0x2b62821c.
Display initialized-none
Using device DeckLink Duo (3)
[DeckLink capture] bmdDeckLinkConfigVideoInputConnection: Input set to: 1
[DeckLink capture] Setting single link by default.
The desired display mode is supported: 1080p59.94
Enable video input: 1080p59.94
[Decklink capture] Audio input set to: embedded
[DeckLink capture] EnableAudioInput: Decklink audio capture initialized sucessfully: 2 channels, 4 Bps, 48000 Hz, codec: PCM
Start capture
DeckLink capture device enabled
Video capture initialized-decklink
Created new RTP session with SSRC 0x410f825e.
Warning: SDP support is experimental only. Things may be broken - feel free to report them but the support may be limited.
Audio sending started.
Frame received (#0) - No input signal detected
    Last message repeated 1 times
[lavcd aud.] Using audio encoder: libopus
uv: src/transmit.cpp:962: void audio_tx_send_standard(tx*, rtp*, const audio_frame2*): Assertion `buffer->get_channel_count() == 1' failed.

UltraGrid has crashed (Aborted).

Please send a bug report to address ultragrid-dev@cesnet.cz.
You may find some tips how to report bugs in file doc/reporting_bugs.md distributed with UltraGrid.
Aborted (core dumped)`

When I run the command without setting the audio channels it works fine, but from what I see, the audio is only in mono.

**Comment by TheSashmo** [comment]
Just to add, when running without the channels command, I am noticing lipsync issues.  Its not in time.

**Comment by TheSashmo** [comment]
Update adding --audio-delay=16  helped it out.

**Comment by MartinPulec** [comment]
Hi, well those are not completely bugs:

1. this transmission currently doesn't support more than 1 channel for OPUS, but there should not be an abort, I confirm
2. A/V sync is commonly not dealt with UltraGrid, it is assumed that as the latency is "low" it synchronizes by that fact. It may sound imperfect but the main target of UltraGrid is rather low-latency transmissions than streaming.

**Comment by MartinPulec** [comment]
Point 1. is now fixed - error message is printed instead. You can create a feature request for multiple channels if you wish.

**Comment by MartinPulec** [comment]
Closing for now. If you wish, you can convert it into feature request.
