### ISSUE TITLE
--enable-vp9-highbitdepth

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#153]
according to https://trac.ffmpeg.org/ticket/3271 this flag must be set for 10-bit encoding with VP9 during ffmpeg compile.  

`Note that for 10-bit encoding, you need to set the --enable-vp9-highbitdepth configuration option.
`
This would be a good capability for UG.

**Comment by MartinPulec** [comment]
It actually looks like it is rather a `libvpx` configuration option.

But yes, it may be feasible there, where we compile own FFmpeg, which is currently Linux AppImage. While the codec capability is checked by FFmpeg during runtime, it may be even possible to replace the _libvpx_ binary where we do not build own FFmpeg but I wouldn't do that.

**Comment by alatteri** [comment]
THanks Martin.... I'll try to test that this weekend.  Closing this issue, and if there are any decoder problems I'll start a new one.
