### ISSUE TITLE
Ubuntu 20.04 Build Error Windows X Compile

### ISSUE THREAD

**Issue by mcgurkorama** [CESNET/UltraGrid#164]
I am trying to complile the latest release on Ubuntu 20.04 for Windows using .`/autogen.sh --host=x86_64-w64-mingw32` as directed for NDI support.

There appears to be an issue however as the build fails out with the following error;

`checking for ./glm/glm/glm.hpp... configure: error: cannot check for file existence when cross compiling`

The system compiles the Linux version without error and only seems to fail when the X Compile directive is specified. It appears the AC_CHECK_FILE is responsible for the error. Commenting out the offending section in the configure file gets me past this error, but then throws the same with other modules (zfec being the next one I experienced).
As a note I also notice that the configure script does not detect SDL2 as being installed although the libsdl2-dev packaged is presently installed on the system

**Comment by MartinPulec** [comment]
Hi @mcgurkorama,

thanks, I've pushed a fix for those 2 items (_glm_ and _zfec_) and it looks to be sufficient. Are there any other instances that cause a problem? I've look at the occurrences of `AC_CHECK_FILE` in _configure.ac_ and none of the remaining should be triggered by default. But if you encounter something more, please let us know.

I am a bit confused about the `SDL2` - did you mean that it is not detected when cross-compiling? I guess that it is correct, unless you have some libsdl2-dev package cross-compiled for Windows (I could imagine that multi-arch may have something like `win32` target, but I haven't seen that yet).

Anyways, as for the _NDI_ - it should be possible to link against it in Linux if installed eg. by Wine. I'd however expect that _configure.ac_ would need some tweaks.

**Comment by MartinPulec** [comment]
Closing now for inactivity.
