### ISSUE TITLE
Raspberry Frame buffer

### ISSUE THREAD

**Issue by TheSashmo** [CESNET/UltraGrid#166]
Has anyone had any luck using the frame buffer like omxplayer does to play video directly to the HDMI?

I've done this before tons of times with ffmpeg, but since ultragrid is using a nonstandard rtp I am not able to get omxplayer to play the video without forcing the SDP option, and that breaks my workflow.  

Ideally I'd like to just pass the straight multicast to omxplayer or ultragrid on raspberry but it seems that the only way to do that would be to install a desktop environment, and would prefer not to waste power and memory to run a UIX.

So my questions are:

- is it possible to send video directly to the framebuffer like omxplayer does while running in headless mode?
- I noticed that while testing the -d dummy option that decoding audio and video returned errors on the audio decoding only, but if I disable the audio portion of the stream, the video can decode very well "from what the logs say"  up to 1080p60, but once I add audio, the stats in the decoder begin to show lost packets on the audio portion, but video is perfectly fine.  CPU is at about 50%.

**Comment by TheSashmo** [comment]
If the source has more than 2 channels, the decode on the raspberry throws of errors:

`[Audio decompress] Inequal channel length detected (0 vs 3840)!`

Would be wise to add a mapping feature. I recall reading it somewhere on the wiki.......

**Comment by MartinPulec** [comment]
Hi, 
> So my questions are:
> 
> * is it possible to send video directly to the framebuffer like omxplayer does while running in headless mode?

Yes, it is possible using SDL2 with _RPI_ renderer (AFAIK selected by default). [Some rumors](https://stackoverflow.com/questions/57672568/sdl2-on-raspberry-pi-without-x) say that it is possible using _KMSDRM_ but I didn't make it work. SDL in the [official AppImage](https://github.com/CESNET/UltraGrid/releases/download/continuous/UltraGrid-latest-armhf.AppImage) currently lacks the RPI renderer, because using generic SDL. I'll however try to add version from [this repo](http://archive.raspberrypi.org/debian) that should contain that. Also the RPI needs legacy (G1) video driver to run.

> 
> * I noticed that while testing the -d dummy option that decoding audio and video returned errors on the audio decoding only, but if I disable the audio portion of the stream, the video can decode very well "from what the logs say"  up to 1080p60, but once I add audio, the stats in the decoder begin to show lost packets on the audio portion, but video is perfectly fine.  CPU is at about 50%.

Ugh, that is a bit interesting - do you use compressed or uncompressed audio? In any case, I'd try the opposite. Generally it shouldn't be much demanding - depends on how much channels do you use. If you could paste your commands I may be able to look at it.

**Comment by MartinPulec** [comment]
> If the source has more than 2 channels, the decode on the raspberry throws of errors:
> 
> `[Audio decompress] Inequal channel length detected (0 vs 3840)!`
> 
> Would be wise to add a mapping feature. I recall reading it somewhere on the wiki.......

This is due to network loss, nothing to do much with channel count. On the other hand, if you use less, the losses will be limited (and/or using a compression).
> 
> Correction that is only on the encode. Not available on the decode. :( That would be a feature request to be able to map the incoming audio accordingly to the output. If the source has 16 channels, it would be nice to be able to map the on the output correctly to a special setup based on each receiver setup.

You can look at the `--audio-channel-map` option.

**Comment by TheSashmo** [comment]
> Hi,
> 
> > So my questions are:
> > 
> > * is it possible to send video directly to the framebuffer like omxplayer does while running in headless mode?
> 
> Yes, it is possible using SDL2 with _RPI_ renderer (AFAIK selected by default). [Some rumors](https://stackoverflow.com/questions/57672568/sdl2-on-raspberry-pi-without-x) say that it is possible using _KMSDRM_ but I didn't make it work. SDL in the [official AppImage](https://github.com/CESNET/UltraGrid/releases/download/continuous/UltraGrid-latest-armhf.AppImage) currently lacks the RPI renderer, because using generic SDL. I'll however try to add version from [this repo](http://archive.raspberrypi.org/debian) that should contain that. Also the RPI needs legacy (G1) video driver to run.

Interesting, I will look into this.  One would think that the raspberry would have enough power to handle this since it can do very well with other codecs and similar encoding settings

> 
> > * I noticed that while testing the -d dummy option that decoding audio and video returned errors on the audio decoding only, but if I disable the audio portion of the stream, the video can decode very well "from what the logs say"  up to 1080p60, but once I add audio, the stats in the decoder begin to show lost packets on the audio portion, but video is perfectly fine.  CPU is at about 50%.
> 
> Ugh, that is a bit interesting - do you use compressed or uncompressed audio? In any case, I'd try the opposite. Generally it shouldn't be much demanding - depends on how much channels do you use. If you could paste your commands I may be able to look at it.

H.264 Video compressed, with the lowest settings for HD video. i.e. 4:2:0 8-bit.  and compressed audio AAC or OPUS.

> > If the source has more than 2 channels, the decode on the raspberry throws of errors:
> > `[Audio decompress] Inequal channel length detected (0 vs 3840)!`
> > Would be wise to add a mapping feature. I recall reading it somewhere on the wiki.......
> 
> This is due to network loss, nothing to do much with channel count. On the other hand, if you use less, the losses will be limited (and/or using a compression).

Hmmm, I am a bit doubtful on this one.  Its all on the same lab setup, devices right next to each other on the same switch and no other device shows the same result, and the bitrates are low.  I am doubtful of packet loss.

> 
> > Correction that is only on the encode. Not available on the decode. :( That would be a feature request to be able to map the incoming audio accordingly to the output. If the source has 16 channels, it would be nice to be able to map the on the output correctly to a special setup based on each receiver setup.
> 
> You can look at the `--audio-channel-map` option.

Thanks!  Yes thats the command I was looking at.

BTW I sent you an email a while back, not sure if it went to spam.  Search for Sasha.

**Comment by MartinPulec** [comment]
> > Hi,
> > > So my questions are:
> > > 
> 
> Interesting, I will look into this. One would think that the raspberry would have enough power to handle this since it can do very well with other codecs and similar encoding settings

The abovementioned AppImage now has SDL2 with _RPI_ renderer. I'll perhaps add also _KMSDRM_ - although it didn't work for me, it may for different board or graphic driver selection.

> 
> H.264 Video compressed, with the lowest settings for HD video. i.e. 4:2:0 8-bit. and compressed audio AAC or OPUS.

And how much of the channels there is? 1-2 should be generally safe, 16 perhaps not.

> > This is due to network loss, nothing to do much with channel count. On the other hand, if you use less, the losses will be limited (and/or using a compression).
> 
> Hmmm, I am a bit doubtful on this one. Its all on the same lab setup, devices right next to each other on the same switch and no other device shows the same result, and the bitrates are low. I am doubtful of packet loss.

Well, I meant rather different thing - not the loss caused by the network itself but rather drops caused by loaded receiver - for UDP, the OS itself drops packets if application is not able to process.

> BTW I sent you an email a while back, not sure if it went to spam. Search for Sasha.

Okay, I'll take a look and get back to you.

**Comment by TheSashmo** [comment]
I think we can close this for now... Not sure how much more we can beat this up!

Thanks @MartinPulec
