### ISSUE TITLE
Feature request: Add cumulative audio report as the video decode has

### ISSUE THREAD

**Issue by TheSashmo** [CESNET/UltraGrid#167]
`Video dec stats (cumulative): 47999 total / 47999 disp / 0 drop / 0 corr / 0 missing.
[Decklink display] 150 frames in 5.00483 seconds = 29.971 FPS
SSRC 3e048ae0: 3968/3968 packets received (100%), 0 lost, max loss 0.
SSRC 3cc2d362: 384/384 packets received (100%), 0 lost, max loss 0.`

There isn't a audio decode stats (cumulative), would be good to add it!

**Comment by MartinPulec** [comment]
I've just pushed some basic statistics. Only played/total audio frames are currently displayed. Unfortunately it needs to be in units of frames and not samples - generally we don't have that information if packet is lost.

**Comment by TheSashmo** [comment]
I think thats more than enough.  If there are missing packets, it will show less packets played.  That is more than enough.
