### ISSUE TITLE
An improper locking bug(e.g., deadlock) on the lock server

### ISSUE THREAD

**Issue by ycaibb** [CESNET/UltraGrid#183]
Hi, developers, thank you for your checking. It seems the lock `server` is not released correctly when `!server->initialize` in the function `serverStop`?

https://github.com/CESNET/UltraGrid/blob/e3c926c8ff67586bf74c4cc0763a78c83ede9cf6/src/EmbeddableWebServer.h#L1516-L1525

**Comment by MartinPulec** [comment]
Hi, the upstream for EmbeddableWebServer is [this repository](https://github.com/hellerf/EmbeddableWebServer) so if you wish, you can report it there. Anyways, I am not sure if this can be considered as a bug - there can be as well assert or abort, which would be perhaps better. But from my perspective, calling stop on non-running error is a logic error. It is true, anyways, that while there is a continuation, it shall be unlocked.

**Comment by ycaibb** [comment]
@MartinPulec Thank you for your reply. Indeed, just looking at the code, the lock `server ` should be released anyways.
I would also report this to upstream.

**Comment by MartinPulec** [comment]
Fixed, thanks for reporting!
