### ISSUE TITLE
Simultaneous NDI and SDI output

### ISSUE THREAD

**Issue by pcarrillom** [CESNET/UltraGrid#196]
Hello,

Is there a way to display both NDI and SDI out with one ultragrid receiver?

thanks

**Comment by MartinPulec** [comment]
Hi, yes, you can look at _multplier_ (`-d multiplier:help`). Assuming that the output is eg. with DeckLink, you could be able to use something like:

`uv -d multiplier:ndi#decklink <remote>`

(The order of devices may matter - NDI on macOS needs to be run in main thread which can be achieved by quoting it first.)
