### ISSUE TITLE
Audio corruption

### ISSUE THREAD

**Issue by benroeder** [CESNET/UltraGrid#213]
# Symptom 

UV will generate gaps and glitches (unflow and overflow) in audio wav files. see attached pictures
Full track with transients marked
<img width="1112" alt="fullrecording" src="https://user-images.githubusercontent.com/1080158/154497100-f92e9c80-50c7-44c7-8e88-48baf7cd866b.png">

glitch in sine wave
<img width="1300" alt="glitch1" src="https://user-images.githubusercontent.com/1080158/154497211-83287047-97ef-4850-b242-b28f8dd7a7a2.png">

Gap in audio
<img width="1116" alt="audiogap" src="https://user-images.githubusercontent.com/1080158/154497277-2dc8d4d6-5e74-479b-91d3-a2250ad80bf6.png">

## How to recreate

I have created this on a mac mini running 12.2.1 (M1) and on Macbook Pro 9 (intel)

### M1
	Decklink 8KPro output
	Decklink mini recorder 4K
	Blackmagic drivers 12.2.2a

UV version

	 /Applications/uv-qt.app/Contents/MacOS/uv
	MasterPortDestroyer is armed
	UltraGrid 1.7+ (tags/continuous rev ef0806da built Feb  9 2022 11:24:25)	
	Display device   : none
	Capture device   : none
	Audio capture    : none
	Audio playback   : none
	MTU              : 9000 B
	Video compression: none
	Audio codec      : PCM
	Network protocol : UltraGrid RTP
	Audio FEC        : none
	Video FEC        : none
	
	Display initialized-none
	Video capture initialized-none
	Created new RTP session with SSRC 0x675907f2.
	Exit
	MasterPortDestroyer triggered

output looped to input
![IMG_4916](https://user-images.githubusercontent.com/1080158/154499508-2fd5e8c1-23cb-45ec-9177-48de75576153.jpg)

cli
       
	/Applications/uv-qt.app/Contents/MacOS/uv -t testcard:1920:1080:24:v210:pattern=bars:apattern=sine -d decklink:device=0 -r embedded -s embedded -VV --audio-capture-channels 2  > testsignal.log 2>&1

record with MediaExpress from DeskTopVideo

examine in Davinci Resolve Fairlight package

see[ wav m1 ](https://we.tl/t-n337iMH1fN) via wetransfer

see [logfile](https://we.tl/t-mQ3LcmPdUA) via wetransfer

	grep flow testsignal.log
	[1645099798.618] [Decklink display] audio buffer underflow!
	[1645100719.869] [Decklink display] audio buffer underflow!
	[1645101391.862] [Decklink display] audio buffer underflow!
	[1645103794.303] [Decklink display] audio buffer underflow!
	[1645105038.296] [Decklink display] audio buffer underflow!

No mention of overflow which is what I would have thought created the "glitch"

### Intel
	UltraStudio Monitor 3G
	UltraStudio Recorder 3G
	Blackmagic drivers 12.2.2a

cli
	
	/Applications/uv-qt.app/Contents/MacOS/uv -t testcard:1920:1080:24:v210:pattern=bars:apattern=sine -d decklink:device=1 -r embedded -s embedded -VV --audio-capture-channels 2  > testsignal.log 2>&1

same sort of issues

as @MartinPulec knows this happens under Linux as well.

The above is recreating the issue, but with a CESnet compiled app, no compilation or modification from me

**Comment by benroeder** [comment]
If the option no-low-latency is used I do not get the errors, but I do get many many Dropped / Late frames

**Comment by MartinPulec** [comment]
Hi @benroeder, from my point of view, it is indeed given by the drifting clock of DeckLink device. As for the overflow, have you been able to test code from [this branch](https://github.com/CESNET/UltraGrid/tree/wip-deck-drift)? IIRC, the usage was `-d decklink:drift_fix`. But it is now able to handle only overflows, not underflows. The latter would be possible to add.

Also, I've added _crescendo_ audio pattern. Usage is simply:

`uv -s testcard:crescendo`; or better  
`uv -s testcard:crescendo=4`

(4 means 4x faster volume increase). The idea behind this that if you are able to capture output signal, the pattern better exhibits what happens - eg. in case of gap if the audio frames are dropped (thus the sound would be non-continuous when removing the gap) or there is clock shift (in this case it would be continuous).

**Comment by benroeder** [comment]
Hi @MartinPulec,
I get the following compilation error on that branch, have not had a chance to look at properly yet
`
 make
mkdir -p src/audio/
g++ -g -O2 -I. -std=gnu++17 -fPIC -msse4.1 -pipe -W -Wcast-qual -Wcast-align -Wmissing-declarations -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/x86_64-linux-gnu -I/usr/include/opencv -I/usr/local/include  -I/usr/include/opencv -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I./ext-deps/zfec/zfec -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -g -DHAVE_CONFIG_H -DPATH_PREFIX='"/usr/local"' -DLIB_DIR='"/usr/local/lib"' -Wall -Wextra -Wpointer-arith -DGF_BITS=16 -D_GNU_SOURCE -Isrc -I. -I./src -I./test -Idxt_compress "-I/usr/local/cuda/include"  -I./ext-deps/DeckLink/Linux -I/usr/include/SDL2 -I./glm    -Icineform-sdk/Common/ -MD -c src/audio/types.cpp -o src/audio/types.o
In file included from src/audio/types.cpp:47:0:
src/audio/types.cpp: In member function ‘std::tuple<bool, audio_frame2> audio_frame2::resample_fake(audio_frame2_resampler&, int, int)’:
src/audio/types.cpp:422:32: error: ‘class audio_frame2_resampler’ has no member named ‘resample_to’; did you mean ‘resampler’?
         UNUSED(resampler_state.resample_to);
                                ^
src/debug.h:51:20: note: in definition of macro ‘UNUSED’
 #define UNUSED(x) (x=x)
                    ^
src/audio/types.cpp:422:32: error: ‘class audio_frame2_resampler’ has no member named ‘resample_to’; did you mean ‘resampler’?
         UNUSED(resampler_state.resample_to);
                                ^
src/debug.h:51:22: note: in definition of macro ‘UNUSED’
 #define UNUSED(x) (x=x)
                      ^
Makefile:279: recipe for target 'src/audio/types.o' failed
make: *** [src/audio/types.o] Error 1`

**Comment by MartinPulec** [comment]
I see, it should be fixed now - it was just a compatibility if SpeexDSP was not found. I've fixed it in place and rebased against current master branch. However, compiling the branch without SpeexDSP would be useless, since the speex resampler is used to adjust the sample rate.

**Comment by benroeder** [comment]
Hi @MartinPulec,
I ran the above 
<img width="1729" alt="overview" src="https://user-images.githubusercontent.com/1080158/157838794-7d5dca54-d3bc-4787-a5ff-e49a70ed3da2.png">

and zoomed in
<img width="1718" alt="zoom" src="https://user-images.githubusercontent.com/1080158/157838840-be660d40-0a94-4860-810d-e2c41a0e8953.png">

I see gaps like

<img width="2041" alt="missing" src="https://user-images.githubusercontent.com/1080158/157838939-f8703c75-3f06-4e6d-89c4-f06eedffe5f6.png">

and 
<img width="1851" alt="gap" src="https://user-images.githubusercontent.com/1080158/157838961-6eb1bbd2-23ff-40e2-8f9b-70a1e341f830.png">
and
<img width="1996" alt="missing2" src="https://user-images.githubusercontent.com/1080158/157839224-4e0ca91b-ff27-4749-9831-e6682ef09904.png">

from the log I see

grep flow crescendo.log
    [1646927662.327] [Decklink display] audio buffer underflow!
    [1646927662.407] [Decklink display] audio buffer underflow!
    [1646927662.647] [Decklink display] audio buffer underflow!
    [1646927663.007] [Decklink display] audio buffer underflow!
    [1646927666.329] [Decklink display] audio buffer underflow!
    [1646927840.331] [Decklink display] audio buffer underflow!
    [1646928064.007] [Decklink display] audio buffer underflow!
    [1646928640.331] [Decklink display] audio buffer underflow!
    [1646929928.333] [Decklink display] audio buffer underflow!

log file
[crescendo.log](https://github.com/CESNET/UltraGrid/files/8230691/crescendo.log)

wav file extracted from recorded mov with 
   
   ffmpeg -i crescendo.mov  -vn -acodec copy crescendo.wav

[wavfile](https://we.tl/t-hjzoWqDbNm) via wetransfer

**Comment by MartinPulec** [comment]
I've a bit walked through the data but as far as I understand it, it looks to be doing what is supposed to do, right? It just requests some time to settle the correct rate - it is gradually resampling to 47061, 4798, 47991, 47996 and 47998,8 Hz.

The problem may be the convergence - it overshoots the drift by a great deal at first... Also the final frequency should be closer to 48 kHz (I am deducing from `Sending resample request -2: 12287694/256`. The request -2 actually means that the computed drift is 1/128 Hz lower - this is just an aggressive step to avoid overrun, thus it should be rather something like 47999,3.

I don't have this tested, but what if you used `--param soft-resample 12287822/256` instead of `:drift_fix` _DeckLink_ option?

**Comment by benroeder** [comment]
@MartinPulec we have a pull request coming with a full fix for this issue.

**Comment by benroeder** [comment]
See pull request

**Comment by benroeder** [comment]
fixed in decklink resdampling
