### ISSUE TITLE
Decklink conversion mode on receiver

### ISSUE THREAD

**Issue by mfkenney** [CESNET/UltraGrid#215]
Hello,

I'm running the Linux build of Ultragrid 1.7.2 with a Decklink Studio 4K card and I am getting an "unable to set conversion mode" error on the receive side:

```
$ uv --tool uv -d decklink:device=0:conversion=none -m 8500 10.xx.xx.xx
stat: /tmp/.mount_uvL2Mygo/usr/lib/libselinux.so.1: no version information available (required by stat)UltraGrid 1.7.2 (tags/v1.7.2 rev a06d459a built Jan 18 2022 11:09:59)

Display device   : decklink
Capture device   : none
Audio capture    : none
Audio playback   : none
MTU              : 8500 B
Video compression: none
Audio codec      : PCM
Network protocol : UltraGrid RTP
Audio FEC        : none
Video FEC        : none

[NAT] Private outbound IPv4 address detected and binding as a receiver. Consider adding '-N' option for NAT traversal.
[Decklink display] Using low-latency mode. In case of problems, you can try '-d decklink:no-low-latency'.
[Decklink display] Using device DeckLink Studio 4K
Unable to set conversion mode
Unable to open display device: decklink
Exit
```

Perhaps this is related to Issue #77 ...

**Comment by TheSashmo** [comment]
Why are you setting conversion to none?  If its none, then don't pass the arguement.

**Comment by mfkenney** [comment]
I've tried it both ways, conversion=none and leaving out the argument. It fails with the same error message every time.

--Mike

**Comment by TheSashmo** [comment]
Whats -tool?

The stat message tells you that something is not there.  Are you sure you installed UV correctly?

uv -t decklink:connection=SDI:device=0 -c ibavcodec:codec=H.264:encoder=libx264::bitrate=5000k -s embedded --audio-codec=MP3:sample_rate=48000:bitrate=128k --audio-capture-format channels=8 -l unlimited -m 1316 -P 50000 127.0.0.1

This command should work just fine for you, if not, then you are doing something wrong on your box.  Try starting from scratch.

**Comment by mfkenney** [comment]
Problem solved. Apparently, I need to specify some conversion method when outputting to this board. The default of "none" triggers the error.

**Comment by MartinPulec** [comment]
Hi @mfkenney, thanks for reporting, yes it looks like it is an analogous bug to #77, indeed, except that was on capture. I've fixed the code that the conversion isn't set at all if user doesn't request. Would it be possible to try current [development build](https://github.com/CESNET/UltraGrid/releases/tag/continuous)? I'll perhaps port the fix back later.

**Comment by MartinPulec** [comment]
Hi @mfkenney, thanks for reporting and update. And yes, it is a bug so I've fixed it anyways in current [development builds](https://github.com/CESNET/UltraGrid/releases), also it will later arrive to stable builds. Now, the conversion is never set unless user explicitly requests.

**Comment by mfkenney** [comment]
Hi @MartinPulec, thanks for the update. I will try the development build sometime next week.

**Comment by mfkenney** [comment]
Hi @MartinPulec, I tried the development build and it did indeed fix the problem. Thanks.
