### ISSUE TITLE
Unknown parameter: use-hw-accel

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#223]
Hi 

When did the parameter `use-hw-accel` get removed?  I've found in the past using this on the receiver resulted in lower decoding load and smoother playback.

Thanks.

**Comment by alatteri** [comment]
Whooopps.... nevermind.  Some pre-requisites did not get properly installed prior to compile.  Ignore this.

**Comment by dnahman** [comment]
@alatteri Do you recall what those pre-requisites were?  I'm running into the same problem myself.

Thanks

**Comment by alatteri** [comment]
@dnahman 

This is my full list of dependencies.

sudo -E apt-get -y install libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libva-dev libvdpau-dev libcurl4-nss-dev libssl-dev libsdl2-dev libglew-dev libx265-dev libx265-doc libasound-dev vainfo libspeexdsp-dev intel-media-va-driver-non-free i965-va-driver-shaders libva-drm2 libva2 vainfo libmfx-dev libglfw3-dev libvdpau-va-gl1 libv4lconvert0 libv4l-dev libvpx-dev libx264-dev libsoxr-dev libvulkan-dev

**Comment by dnahman** [comment]
Thanks for the info.  

We are running an older linux distro, with incompatible `glibc` for the AppImage builds, so we are trying to come up with a source build that works with our older libs and nVidia drivers.   I'm building ffmpeg libraries with `nvenc` support, but still can't figure out why `uv` built with cuda/nvenc won't accept the `use-hw-accel` flag.   I'll post if I figure this out, or if you have any other insights they would be appreciated.

Regards

**Comment by alatteri** [comment]
what old distro and why?  The Ubuntu 22 makes this so much easier.

**Comment by dnahman** [comment]
RHEL 7.9.  The production toolset at our facility is currently pegged to that OS, and it takes a long time to turn the big ship.

In any case, if I eliminate the use-hw-accel flag, nvidia-smi still shows that uv is using the GPU, and nvenc is compiled into the ffmpeg libraries, so I *think* things are running correctly.  I'll be doing some more tests tomorrow, both objective and subjective to confirm.  I'll have to set aside some time to dig deeper into the code and figure out what it all means.

PS, we are also running release/1.7.   Next step after getting parity with our old builds would be to test the new release in production.

Cheers
david
