### ISSUE TITLE
Disable loopback while running application

### ISSUE THREAD

**Issue by TheSashmo** [CESNET/UltraGrid#238]
When I run an instance of Ultragrid on decklink port 0, I get a loopback on port 1, until I run another instance of Ultragrid to use port 1.  This might be a decklink issue, but I have never seen that on any other non Ultragrid application.  Is there an option I am missing, or is that a feature?

**Comment by MartinPulec** [comment]
You mean the passthrough mode? This is AFAIK toggled on by default for DeckLinks. On the contrary, UltraGrid [disables it](https://github.com/CESNET/UltraGrid/commit/2345e0e9393cae97d4814fa5f07e7c05d64642c0) in recent development versions by default.

I am not completely sure from your description about the actual setup, however. Which device it is? Playback or capture? It may be also something else, like A/B playback of device profile setting for models supporting that (eg. _8K Pro_). However I am not aware that there is some special non-default setting in UltraGrid in this direction.

**Comment by TheSashmo** [comment]
Quite straight forward.

Device #1 is setup to send to device #2.  On device #1 the output port is showing the same as the input port.  i.e. decklink port 0 has a loop through of port 1.

I have not seen any option in the decklink to disable this.

**Comment by MartinPulec** [comment]
Which version? As I wrote, development version of UltraGrid now toggles the passthrough off by default. It is option `-t decklink:nopassthrough`, but as it is default, it is pointless to use it as such. However you can use `-t decklink:passthrough` (enable) or `-t decklink:passthrough=keep` (device defaults).

**Comment by TheSashmo** [comment]
I'm using an older version so I will have to check.  Thanks Martin.

**Comment by MartinPulec** [comment]
I see, well, only the default (== _to disable_) has changed recently, the option itself has been there already some time ago, so it is possible that `-t decklink:nopassthrough` would do the job in the end.
