### ISSUE TITLE
[Feature Request] SDL2 window creation options : no border / size / position 

### ISSUE THREAD

**Issue by Code-ScottLe** [CESNET/UltraGrid#24]
UltraGrid currently defaults SDL2 SDL_CreateWindow call to center of the screen with the video resoltion (width + height) as default size/position. It would be nice if these parameters can be passed in by users when running the command with fall back to those default values.

Also if we can also have an option to remove the title bar off the window with either `SDL_NOFRAME` flag or possibly the new `SDL_WINDOW_BORDERLESS` flag (https://wiki.libsdl.org/SDL_CreateWindow), this will give us more possibility of being able to inline the video within others application better. 

Just not sure if we want to have custom input flag, or just straight up enables users to be able to pass in [SDL_WindowFlag](https://wiki.libsdl.org/SDL_WindowFlags) which gives a lot more power (Always On top is also a nice one), but the syntax isn't that friendly.

**Comment by MartinPulec** [comment]
I've added options "nodecorate", "fixed_size[=WxH]" and "windows_flags", see the commit aaec6c9d and the previous commits. Build is again [here](https://github.com/CESNET/UltraGrid/releases/download/nightly/UltraGrid-20190627-devel-win64.zip). I haven't tested the much, especially window_flags – it should accept bitmask of those flag values, you need perhaps to look them up in header (in decadic or hexadecimal if prefixed with 0x, octal should work as well if you wish).

Again, it is devel branch and build, so it is not yet present in master.

**Comment by Code-ScottLe** [comment]
Can you also add the position of the window when creating it? (x,y) value when creating window.

**Comment by MartinPulec** [comment]
This should not be a problem. Try `pos=<x>,<y>` with the build [here](https://github.com/CESNET/UltraGrid/releases/download/nightly/UltraGrid-20190628-devel-win64.zip).

**Comment by alatteri** [comment]
Hey guys.... along these lines, would it be possible for UG to maintain picture aspect ratio when drag resizing of the window?  Currently it is free form and someone can pull it to any size resulting in black borders.  Sorry I have had time to test the other features yet...still busy for the next few weeks.  Thanks!

**Comment by MartinPulec** [comment]
@alatteri I don't think it is directly possible, I haven't found any direct possibility to do that. It could be possible to react to user SDL_WINDOWEVENT_RESIZED and resize the window programatically to keep the aspect.

**Comment by MartinPulec** [comment]
@alatteri I don't think it is directly possible, I haven't found any direct possibility to do that. It could be possible to react to user SDL_WINDOWEVENT_RESIZED and resize the window programatically to keep the aspect.

**Comment by alatteri** [comment]
OK...It is not a critical issue anyway, just a small annoyance.

> @alatteri I don't think it is directly possible, I haven't found any direct possibility to do that. It could be possible to react to user SDL_WINDOWEVENT_RESIZED and resize the window programatically to keep the aspect.

**Comment by MartinPulec** [comment]
@alatteri You can check [this branch](https://github.com/MartinPulec/UltraGrid/tree/sdl2-keep-aspect). As I expected it is not ideal because especially when trying to resize in a wrong direction, SDL wrestles with the user for the window size.

**Comment by alatteri** [comment]
Thanks Martin...Would you be able to provide macOS & windows binary of this branch?  I'm fine compiling for linux (which we use as the UG server) but the I'm not familiar with compiling for the other platforms which we use for the clients.  

> @alatteri You can check [this branch](https://github.com/MartinPulec/UltraGrid/tree/sdl2-keep-aspect). As I expected it is not ideal because especially when trying to resize in a wrong direction, SDL wrestles with the user for the window size.

**Comment by MartinPulec** [comment]
I wouldn't do that now. I do not consider it a working solution. It is rather a kickoff but there is a missing logic how to intelligently resize the window. As such, if no one will be interested in implementing that, it is rather to be removed.

> Thanks Martin...Would you be able to provide macOS & windows binary of this branch? I'm fine compiling for linux (which we use as the UG server) but the I'm not familiar with compiling for the other platforms which we use for the clients.
>

**Comment by MartinPulec** [comment]
@alatteri In the end it is implemented in the devel branch in commit 7f10bbc1, but it is currently only optional and must be enabled explicitly with the option `keep-aspect`.

**Comment by MartinPulec** [comment]
Aforementioned features are now included in master and are present in regular builds.

**Comment by alatteri** [comment]
> @alatteri In the end it is implemented in the devel branch in commit [7f10bbc](https://github.com/CESNET/UltraGrid/commit/7f10bbc11350f99fecf2f438728ec0d874383b04), but it is currently only optional and must be enabled explicitly with the option `keep-aspect`. Devel build is [here](https://github.com/CESNET/UltraGrid/releases/download/nightly/UltraGrid-20190708-devel-win64.zip) (until it reaches master).

Just had a change to test keep-aspect.  It works fine.  Please leave the functionality in.  Thanks.

**Comment by MartinPulec** [comment]
Sure, no problem, it is supposed to remain as an option in UltraGrid. It is just not enabled by default because the behavior is a bit uncomfortable (at least in Linux) since is not smooth. But I think that is not only UltraGrid issue, I've noticed that also in other SDL applications that try to keep aspect (eg. dosbox-x) behave similarly.
