### ISSUE TITLE
High CPU usage for audio-only uncompressed transmission

### ISSUE THREAD

**Issue by reduzent** [CESNET/UltraGrid#252]
When using `uv` for an audio-only transmission with `--audio-codec PCM`, the `uv` process saturates a full CPU core. Given that no complex encoding is involved, I'd expect `uv` to consume much less cycles. 

Client A (nl-11852.lan):

```
UltraGrid-1.7.6-x86_64.AppImage --tool uv -r jack -s jack --audio-codec PCM --audio-capture-format channels=2 -P30104:11064:5016:5014 frank.lan
```

Client B (frank.lan):

```
UltraGrid-1.7.6-x86_64.AppImage --tool uv -r jack -s jack --audio-codec PCM --audio-capture-format channels=2 -P30104:11064:5014:5016 nl-11852.lan
```

On both clients `htop` shows that `uv` is using ~100%.

Tested on:

-  Ubuntu 20.04 (frank.lan)
-  Ubuntu 22.04 (nl-11582.lan)

With:

- UltraGrid 1.7.6 (AppImage)

**Comment by mpiatka** [comment]
This was caused by busy-waiting for audio samples on the sender. It should now be fixed on today's continuous builds.

**Comment by reduzent** [comment]
I confirm this issue is fixed. Thank you very much!
