### ISSUE TITLE
Unable to compile with NDI (Ubuntu 18.04)

### ISSUE THREAD

**Issue by mintopia** [CESNET/UltraGrid#26]
Hi, I'm trying to build UltraGrid on Ubuntu 18.04 and it's unable to add NDI when configuring the build:

```
checking Processing.NDI.Lib.h usability... yes
checking Processing.NDI.Lib.h presence... yes
checking for Processing.NDI.Lib.h... yes
checking for NDIlib_initialize in -lndi... no
configure: error: NDI not found!
```

I've followed the instructions on the wiki but no luck so far.

**Comment by MartinPulec** [comment]
Hi Jessica,

it looks like the configure script is either unable to find or link the NDI lib. If you followed the [instructions](https://github.com/CESNET/UltraGrid/wiki/Compile-UltraGrid-(Source)#NDI), it could be be a llinking problem. Can you provide the generated `config.log`?

Thanks,
Martin

**Comment by mintopia** [comment]
Here you go!

[config.log](https://github.com/CESNET/UltraGrid/files/3405314/config.log)

**Comment by MartinPulec** [comment]
Okay then, it looks like it really cannot find the library. Assuming that `libndi.so` is in `/usr/local/lib` it is possible that it isn't part of default look-up locations in the system. Would it be possible try to add /usr/local/lib to `LIBRARY_PATH` and re-run configure to see if it is the case?

    export LIBRARY_PATH=${LIBRARY_PATH:+"$LIBRARY_PATH:"}/usr/local/lib
    ./autogen.sh --enable-ndi

**Comment by mintopia** [comment]
Turned out the issue is when I copied the files across to lib, I didn't copy the symlinked files, so it had a broken symlink to libnsi.3.8.0.so.

Copied those across and it worked! Thank you for all the support.

**Comment by MartinPulec** [comment]
I see, well, in that case it turned out that it was not correctly in the instructions because those steps expected the libndi.so to be a regular file, not a symlink (perhaps it was so at the time of writing those instructions).

Thanks for pointing out! I've already fixed that.
