### ISSUE TITLE
Control Port API Request

### ISSUE THREAD

**Issue by TheSashmo** [CESNET/UltraGrid#261]
@MartinPulec  Is it possible to enable the real time compression change at the sender side so that it is possible to change the encoded bitrate without having to restart the process?

When I try to use the control api suggestion from the wiki, it throws a message "202 Accepted (receiver not yet exists)" so I am guessing this is only to be used at the reflector?

**Comment by MartinPulec** [comment]
How do you do that? Using:

    $ uv -t testcard --control-port 8888 -c libavcodec
    $ echo "compress libavcodec:encoder=libx264:bitrate=10M" | nc localhost 8888

works for me.

**Comment by TheSashmo** [comment]
I found my issue.  Fat fingers. Thanks.

echo "compress libavcodec:encoder=libx264:bitrate=10M" | nc localhost 8888
vs.
echo "compresss libavcodec:encoder=libx264:bitrate=10M" | nc localhost 8888

**Comment by MartinPulec** [comment]
> vs. echo "compresss libavcodec:encoder=libx264:bitrate=10M" | nc localhost 8888

that's funny, because when I tested it, I also used the "3s" first
