### ISSUE TITLE
Release 1.7.7 and current build broken on OSX 11.6.8

### ISSUE THREAD

**Issue by maybites** [CESNET/UltraGrid#262]
when issuing folloring command:

`/Applications/UltraGrid/continuous/uv-qt.app/Contents/MacOS/uv -t testcard:80:60:1:UYVY -d gl`

I get:

```
dyld: Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Applications/UltraGrid/continuous/uv-qt.app/Contents/MacOS/../libs/libopencv_core.4.6.0.dylib (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib

zsh: abort      /Applications/UltraGrid/continuous/uv-qt.app/Contents/MacOS/uv -t  -d gl
```

I get the same error when using current 1.7.7.

Plus:

In both cases double clicking uv-qt.app crashes, saying:

`Ultragrid crashes when invoked without arguments!`

**Comment by MartinPulec** [comment]
Confirmed, GitHub has switched the latest _macOS_ bild runners to _12 Monterey_ which made the builds incompatible with version _11_  and lower.

I've switched it back to 11 so it now works with macOS 11.x again (both _continuous_ and _1.7.7_; tested on macOS 11.7.1). (For more ancient macOS version there is designated [the alternative macOS build](https://github.com/CESNET/UltraGrid/releases/download/continuous/UltraGrid-nightly-alt.dmg).)

**Comment by maybites** [comment]
I can confirm the fix. Thanks!
