### ISSUE TITLE
[Feature Request] Use NDI as a Display device

### ISSUE THREAD

**Issue by mintopia** [CESNET/UltraGrid#28]
As NDI can be used as a capture device, it would be great to be able to use NDI as a display device as well.

**Comment by MartinPulec** [comment]
I've added some basic implementation of the NDI display – it is quite rudimentary but worked quite fine in a basic setup. I didn't tested it extensively but it would be great if you can look at it and eventually provide some feedback. It supports only few codecs now as well.

**Comment by MartinPulec** [comment]
Closing for thread inactivity.

**Comment by MartinPulec** [comment]
Closing now for thread inactivity.
