### ISSUE TITLE
issues with vulkan_sdl2 display

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#291]
Hello,
I am reporting 2 issues with vulkan_sdl2 display

1)
When using vulkan_sdl2 as display surface, it is introducing horizontal pixel tearing.  This is not related to Vsync, as this happens even on totally static frames.   Switching to sdl surface, the problem does not happen.  vulkan_sdl2 is preferred since it can properly display as 10bit surface.   See screenshots 1175 and 1176.  Zoom in to the jpeg and it becomes very clear.

2) If fullscreen option is not used, vulkan will display as a small portion of the frame even though the input signal and the physical monitor has matching resolutions.  See screenshots 1177 and 1178.  Input signal and monitor both have native resolutions of 3840x2160.   -d sdl displays properly but -d vulkan_sdl2 is shrunken.  Now in real use case, I do always use :fs, but I thought I would bring this up as it may be related to the first issue

![IMG_1175](https://user-images.githubusercontent.com/625982/216856670-687e6cc9-6a93-4da1-9d38-413917263ecb.jpeg)
![IMG_1176](https://user-images.githubusercontent.com/625982/216856673-9d3fa670-da3c-4cf6-a8c8-460b328c65b0.jpeg)
![IMG_1177](https://user-images.githubusercontent.com/625982/216856676-fbac66ab-82d9-471e-a43a-feb2caf29f3b.jpeg)
![IMG_1178](https://user-images.githubusercontent.com/625982/216856680-f0de4850-7bf9-4c05-b864-8853f26eca41.jpeg)

**Comment by alatteri** [comment]
and here is the source PNG that I used to test with.


![45_degree_grid_UHD](https://user-images.githubusercontent.com/625982/216857129-464ad02f-dcaf-483e-907b-e5ff8361109f.png)

**Comment by mpiatka** [comment]
Hello,

thanks for reporting! The pixel tearing was an issue with the R10k shader conversion and should be now fixed.

The second point is not really a bug, but rather an inconsistency in behavior. The vulkan display simply never changes the window size depending on the video. Automatic resizing could be implemented if there is a demand for it.

**Comment by alatteri** [comment]
No need as :fs is the only behaviour I use.   I just didn't know if it was also a symptom of the first bug.   Thanks!!

> The second point is not really a bug, but rather an inconsistency in behavior. The vulkan display simply never changes the window size depending on the video. Automatic resizing could be implemented if there is a demand for it.

**Comment by alatteri** [comment]
[2023-02-06 08:06:30] [video dec.] Detected internal codec: Y416
[2023-02-06 08:06:30] [display] Successfully reconfigured display to 3840x2160 @24.00p, codec Y416
[2023-02-06 08:06:30] [lavd] Selected pixel format: yuv444p10le

**Comment by mpiatka** [comment]
Right, sorry my bad. The issue was actually the same, just in another shader. Today I pushed the fixes for the remaining shaders, so it should hopefully work correctly now.

**Comment by alatteri** [comment]
Perfect.  Thanks!!!
