### ISSUE TITLE
additional default settings for hevc_qsv

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#294]
Hi,

According to the intel people, these are some additional setting to help latency that might be good to set as default:

> There are some parameters affect latency. If you want low latency you can set async_depth to 1 and set bf to 0 (no b frames).
https://github.com/intel/cartwheel-ffmpeg/issues/230#issuecomment-1432681842

**Comment by MartinPulec** [comment]
>  If you want low latency you can set async_depth to 1

done

B-frames count is always set to 0 with UltraGrid.
