### ISSUE TITLE
inverted colors with H264

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#30]
Hello,

I am testing master on Ubuntu 19.
With H.264 I am getting inverted colors.  All other codecs are displaying correctly.
See attached screenshots.

`ultragrid@slumjuice:~/devel/UltraGrid/bin$ uv -l auto -t v4l2 -c libavcodec:codec=H.264 192.168.101.29
UltraGrid 1.5+ (tags/nightly rev 2059a941 built Aug  8 2019 04:58:00)

Display device   : none
Capture device   : v4l2
Audio capture    : none
Audio playback   : none
MTU              : 1500 B
Video compression: libavcodec:codec=H.264
Audio codec      : PCM
Network protocol : UltraGrid RTP
Audio FEC        : none
Video FEC        : none

Created new RTP session with SSRC 0x4fbbca24.
Display initialized-none
vidcap_v4l2_init
Enable video input: 1920x1080 30.000000 fps progressive, codec RGB
Video capture initialized-v4l2
Created new RTP session with SSRC 0x17ff9a99.
[lavc] Using codec: H.264, encoder: libx264rgb
[lavc] Setting CRF to 22.00.
[lavc] Setting preset to veryfast.
[libx264rgb @ 0x7ff7fc000d80] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264rgb @ 0x7ff7fc000d80] profile High 4:4:4 Predictive, level 4.0, 4:4:4 8-bit
[lavc] Selected pixfmt: rgb24

[V4L2 capture] 150 frames in 5.00104 seconds = 29.9937 FPS
[V4L2 capture] 150 frames in 5.00001 seconds = 30 FPS
[libx264rgb @ 0x7ff7fc000d80] frame I:17    Avg QP:12.76  size:1236334
[libx264rgb @ 0x7ff7fc000d80] frame P:312   Avg QP:13.48  size: 31502
[libx264rgb @ 0x7ff7fc000d80] mb I  I16..4:  0.4% 13.1% 86.5%
[libx264rgb @ 0x7ff7fc000d80] mb P  I16..4:  0.0%  2.3%  0.0%  P16..4:  8.0%  0.8%  0.1%  0.0%  0.0%    skip:88.8%
[libx264rgb @ 0x7ff7fc000d80] 8x8 transform intra:38.6% inter:45.8%
[libx264rgb @ 0x7ff7fc000d80] coded y,u,v intra: 99.1% 98.6% 99.7% inter: 2.9% 4.0% 3.6%
[libx264rgb @ 0x7ff7fc000d80] i16 v,h,dc,p: 17% 49% 17% 17%
[libx264rgb @ 0x7ff7fc000d80] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 13% 65% 14%  1%  1%  1%  2%  1%  3%
[libx264rgb @ 0x7ff7fc000d80] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 13% 27%  7%  7%  9%  7% 10%  7% 12%
[libx264rgb @ 0x7ff7fc000d80] kb/s:22501.900`

<img width="1552" alt="h264" src="https://user-images.githubusercontent.com/625982/62679370-15cd6e00-b969-11e9-9641-2924e336e757.png">

With H.265

<img width="1552" alt="h265" src="https://user-images.githubusercontent.com/625982/62679371-16660480-b969-11e9-9818-485f339e913b.png">

**Comment by MartinPulec** [comment]
Hi Alan, that was a dumb error in color transformations – libavcodec takes GBR and not BGR, which was assumed. This should be fixed now in master, also binary packages should be rebuilt (except of Windows, which currently doesn't build, due to some issues with migrating to MSVS 2019).

**Comment by MartinPulec** [comment]
Windows version should be rebuilt now as well.

**Comment by alatteri** [comment]
confirmed.  Thanks!!
