### ISSUE TITLE
'unlimited' is not a number

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#300]
```
uv -l unlimited -t testcard
UltraGrid 1.8+ (tags/continuous rev a43168e built Mar  5 2023 23:28:47)

'unlimited' is not a number
Invalid bitrate unlimited!

```

**Comment by alatteri** [comment]
https://github.com/CESNET/UltraGrid/wiki/Traffic-shaping

disabled traffic shaper:

uv -l unlimited

Turns off traffic shaper. This can be useful because it saves performance used for traffic shaping (it uses busy waiting to produce inter-packet intervals). Traffic shaper can be safely turned of either if the traffic is low (let say few Mbps) or you have homogenous network - eg. 1 GE end-to-end connectivity.

**Comment by MartinPulec** [comment]
thanks a lot for reporting that, I've just fixed that
