### ISSUE TITLE
Unhandled Exception Error in UltraGrid 1.8.1 upon GUI launch

### ISSUE THREAD

**Issue by mkewman** [CESNET/UltraGrid#302]
Launched the GUI via both commandline and immediately received a "uv-qt.exe has stopped working" error.  Windows 10 on a Lenovo Thinkpad T420 with an Core i7.

debug shows:

`Unhandled exception at 0x00007FFFBD3FF830 (Qt6Gui.dll) in uv-qt.exe: 0xC000041D: An unhandled exception was encountered during a user callback.`

**Comment by mpiatka** [comment]
Hello,
it seems like T420s came with Intel graphics 3000 + nvidia. The Intel GPU supports only OpenGL 3.1 on Windows, while the GUI needs at least 3.3. Could you please confirm which GPU are you running with?

If you have an nvidia gpu, it may be possible to run the GUI by switching to discrete graphics and disabling NVIDIA Optimus in the BIOS.

**Comment by mkewman** [comment]
Yup Intel 3000 graphics.  This would also explain why it doesn't work on some other boxes we've tried.  I'll throw a GPU on another box that can handle at least 3.3.

Thanks for the info!

**Comment by MartinPulec** [comment]
Just for the record – UG would run on Intel HD 3000 in Linux, because OpenGL 3.3 is supported there (I am using one by myself).
