### ISSUE TITLE
Vulkan not properly reconfiguring itself when input stream size changes.

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#303]
Hello,

When using `vulkan_sdl2:fs` it does not properly scale input stream if the stream size changes from the initial size at the time UG was launched.

See the below video. Sorry for poor quality but I had to compress it a lot to fit the GitGub 10MB max.

https://user-images.githubusercontent.com/625982/227746843-fc23bac0-a355-4c73-b0ca-9b5823d57dc9.mp4

**Comment by MartinPulec** [comment]
Hi Alan, you didn't specify steps to reproduce but after some investigation it seems to be Y416-specific (for UYVY only if format is not supported natively by GPU). It should be fixed now (continuous AppImage will be rebuilt tomorrow).

**Comment by alatteri** [comment]
Sorry for the late reply and not making the original issue more clear.  But you got it anyway.  This is fixed.  Thanks again!!!
