### ISSUE TITLE
[messaging] Warning: infinite wait for module without msg notifier. Please report!

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#307]
hd-rum from master is not working.

```
 hd-rum-transcode 20M 5004 -P 5104 127.0.0.1
Module "sdl" (class 5) multiple initialization!
Module "testcard" (class 4) multiple initialization!
UltraGrid 1.8+ (tags/continuous rev 0d679a3 built Apr  8 2023 15:10:35)

using UDP send and receive buffer size of 20971520 bytes
initializing packet queue for 2621 items
listening on *:5004
[messaging] Warning: infinite wait for module without msg notifier. Please report!
```

**Comment by alatteri** [comment]
using and old commit of hd-rum works fine though.

/hd-rum-transcode 20M 5004 -P 5104 127.0.0.1
UltraGrid 1.8+ (tags/continuous rev c189087 built Feb  4 2023 20:53:29)

using UDP send and receive buffer size of 20971520 bytes
initializing packet queue for 2621 items
listening on *:5004
Received 10261234 bytes in 5.0095 seconds = 16.3 Mbps.
Received 12710815 bytes in 5.00057 seconds = 20.3 Mbps.

**Comment by MartinPulec** [comment]
Thanks for the report, I can confirm that it occurs always and I know what is the reason. It is actually caused by some changes in UltraGrid itself. While the reflector shares the code, there arose some incompatibility that was unfortunately not caught. The fix requires however few rewrites so I hope that it could be done in next few days.

**Comment by MartinPulec** [comment]
I've just pushed fixes that should fix the issue, as being said, it needed slight rewrite so hopefully it won't break something else.

**Comment by alatteri** [comment]
still seems to not be working:

```
[2023-04-15 09:21:43] Module "sdl" (class 5) multiple initialization!
[2023-04-15 09:21:43] Module "testcard" (class 4) multiple initialization!
[2023-04-15 09:21:43] UltraGrid 1.8+ (tags/continuous~43 rev 0d679a3 built Apr 15 2023 09:19:57)
[2023-04-15 09:21:43] 
[2023-04-15 09:21:43] using UDP send and receive buffer size of 83886080 bytes
[2023-04-15 09:21:43] initializing packet queue for 10485 items
[2023-04-15 09:21:43] listening on *:5004
[2023-04-15 09:21:43] [messaging] Warning: infinite wait for module without msg notifier. Please report!
```

**Comment by alatteri** [comment]
Thanks !!!
