### ISSUE TITLE
Audio source specification for vidcap switcher

### ISSUE THREAD

**Issue by MartinPulec** [CESNET/UltraGrid#318]
Using video capture _switcher_ allows only one global<sup>[2]</sup> setting of audio input device, eg.:

    uv -s embedded -t switcher -t testcard -t decklink -t decklink:device=1  # or
    uv -s portaudio -t switcher -t testcard -t decklink -t decklink:device=1

First case works (allows switching) but it doesn't allow setting different input connector (_analog_/_AESEBU_) for second decklink (indexed _1_). <del>, on contrary, if _analog_ was set, it won't work for testcard, which currently implements _embedded_ only (but it doesn't unsuccessfully initialize, other devices may).</del> <sup>[1]</sup>:

`uv -t switcher -s analog -t decklink -s embedded -t decklink:device=1` _doesn't_ work (both decklinks need to use either _embedded_ or _analog_)

Second line works normally as assumed (portaudio is used all the time regardless video switching).

<sup>[1]</sup> no longer valid since 594e6493
<sup>[2]</sup> "global" means that "embedded" is applied to all devices and audio will be switched alongside with video; if used "portaudio" instead, _portaudio_ is a standalone device, so audio won't be switched (portaudio will be used all the time)

**Comment by TheSashmo** [comment]
Let me explain the use case, and maybe it will give you guidance on how it could work.

There are times when a client is not giving us any signal or source.  So in a traditional workflow the path needs to be "Active" and sending some sort of signal.

What I was trying to aheive was have some sort of testcard, or recorded file, that is in the proper frame rate and resolution, with audio, of what the client is expecting, and just switch that source to another input using the switcher.  All of this without having to restart the UG pipeline.

**Comment by MartinPulec** [comment]
So in context of this issue which audio you want to send? It is a bit unclear to me from the above, for video - I've (also from #316) understood that decklink + (one?) another device (testcard or file), right?

If so, I suppose that you'd perhaps want to send embedded audio either from one or the another device, regardless if the input is decklink or the fallback?

If the above holds, namely that you want to send embedded audio from the video source which it is switched to, we could come back to remaining issues in the original bug report because I believe that this should already work in UG, just pass one `-s embedded` parameter to UG (the position doesn't matter).

**Comment by MartinPulec** [comment]
Since a25b285, audio connections (analog/AESEBU/embedded) can be specified for vidcaps individually as described [in wiki](https://github.com/CESNET/UltraGrid/wiki/Video-Switcher#audio). This applies to audio connection specifications only, if using standalone audio device (like PortAudio), only that one device can be used (audio not switched). For the time being, I don't think that this is necessary to implement.

**Comment by MartinPulec** [comment]
Since **audio connection** can now be specified per **vidcap** input, I am closing this now. Only _audio connection_ linked to a vidcap is possible to use in this way but I think that this was the requested behavior in the original bug report (#316).
