### ISSUE TITLE
Ultragrid crashes windows computer

### ISSUE THREAD

**Issue by maybites** [CESNET/UltraGrid#319]
Hi

I encounter a reproducable crash (und subsequent freeze) on my machine with the latest Ultragrid Release.

It happens when I try to send a 4k Spout stream with the following CLI command:

`--param log-nocolor -P11032 -t spout -c libavcodec:codec=H.264:bitrate=80M 10.128.96.104`

It doesn't happen with the MJPEG codec..

I can provide the memory dump file or access to my machine if required.

**Comment by MartinPulec** [comment]
Closing didn't get feedback how to reproduce, feel free to reopen if still the issue.

**Comment by maybites** [comment]
Yeah, I know. I wasn't able to reproduce on anther machine.
