### ISSUE TITLE
Problems with AJA HDMI playback

### ISSUE THREAD

**Issue by MartinPulec** [CESNET/UltraGrid#32]
HDMI playback over HDMI doesn't work flawlessly yet, issues:

1. audio doesn't work over HDMI at all (but neither does with SDK `ntv2player` or `ntv2player8k`)
2. HDMI playback over different channels than 1 doesn't work

**Comment by MartinPulec** [comment]
Submitted a ticket #4170 to AJA with question regarding the first issue.

**Comment by MartinPulec** [comment]
AJA SDK [15.5](https://sdksupport.aja.com/index.php?/News/NewsItem/View/47/ntv2-sdk-155-released) was released - should be tested with that.

**Comment by erichorwitz** [comment]
I am currently attempting to get this working however I cannot seem to get it working. Using 15.5.1.1 aja ADK with a Kona 3G

**Comment by MartinPulec** [comment]
I've just noticed that the ticket/question opened by AJA didn't progress because my e-mail response was not taken by the ticket system. I've reposted via web, hopefully it will progress somehow.

**Comment by MartinPulec** [comment]
Audio should now be working. Ntv2player with Kona 5 connected to DeckLink produces correctly audio for me. According to the support the problem might be that when no HDMI EDID is detected, output is set to DVI (no audio). Also firmware update might help. In UltraGrid now the HDMI output is forced.

@erichorwitz, If it still won't work, would it be possible to [generate a log](https://sdksupport.aja.com/index.php?/Knowledgebase/Article/View/how-to-generate-a-support-log)?

**Comment by MartinPulec** [comment]
Also problem 2 looks like being no longer present with AJA Kona 5, current firmware and SDK.

**Comment by erichorwitz** [comment]
I can confirm updating kona3g firmware resolves audio on HDMI

**Comment by MartinPulec** [comment]
Closing now - not sure if issues are still valid.
