### ISSUE TITLE
Feature request to enable disable record from control port

### ISSUE THREAD

**Issue by TheSashmo** [CESNET/UltraGrid#325]
Considering that I have started to use the record feature a lot, I was not able to find any documentation that allowed me to enable or disable recordings via the control port.  I think this would be a great addition to enable recordings on the fly without having to restart the UG session.

**Comment by MartinPulec** [comment]
You can press **Ctrl-x e** to toggle export. Isn't this sufficient?

**Comment by TheSashmo** [comment]
> You can press **Ctrl-x e** to toggle export. Isn't this sufficient?

Well, yes it could, but the issue is it will record it to the default directory where UG is located.   

Additionally, if I supply the command line option --record=/location  it will start recording right away, which I don't want.

P.S. the wiki needs to be updated to show  "location recording" needs to have = next to it.

**Comment by MartinPulec** [comment]
> Well, yes it could, but the issue is it will record it to the default directory where UG is located.
> 
> Additionally, if I supply the command line option --record=/location it will start recording right away, which I don't want.

Well, for that case, you can specify `--record=<dir>:paused`. It won't even create the directory until launched.

> 
> P.S. the wiki needs to be updated to show "location recording" needs to have = next to it.

True, I've already fixed. I'll also update that wiki page.

**Comment by TheSashmo** [comment]
Well thats great!  I didn't know that there was that option!  I didnt even see it in the code!  Maybe I am going blind.
