### ISSUE TITLE
Audio and Video display in single pipe

### ISSUE THREAD

**Issue by mikekoetter** [CESNET/UltraGrid#333]
How difficult would it be to add a display that could output the audio and video together in something like the NUT format over or unix or fifo pipe that could easily be brought into FFMPEG?

_Originally posted by @mikekoetter in https://github.com/CESNET/UltraGrid/discussions/191#discussioncomment-6787400_

**Comment by MartinPulec** [comment]
I think we can add a _file_ output using FFmpeg libavformat quite easily, which would be able to output NUT, quite easily.

**Comment by mikekoetter** [comment]
does a file output already exist, or would this be a new -protocol option like sdp?

**Comment by MartinPulec** [comment]
> does a file output already exist, or would this be a new -protocol option like sdp?

It doesn't, but I believe that it won't be difficult to implement, so we could be able to implement it during next week. It won't be a _protocol_ but rather a _display_.

**Comment by txtpauld** [comment]
Hello!  I would also love this feature to be able to stream the uncompressed video from a decklink card using this nut format.  

We would like to be able to take a decklink rgb 10 bit or ycbcr 422 10 bit signal and send it via ultragrid and then also to ffmpeg.  

We would like to keep it uncompressed when it gets to ffmpeg so we can compress it using workflows we have already developed that make multiple renditions of the media with different audio and video formats without having to re encode everything in separate ffmpeg processes.  

12bit rgb will be coming down the pipe as well in the future. 

Thanks for the help!

**Comment by MartinPulec** [comment]
I've just added the implementation of _file_ video display, which is basically a libavformat muxer, to the Git (thus being present in [continuous builds](https://github.com/CESNET/UltraGrid/releases/tag/continuous)).

Remarks:

1. the output format (both container and codecs) are deduced from given output **file name**: 

    a. if it is _unknown_ or **NUT**, the NUT container will be used with _uncompressed_ audio and video. For the video, FFmpeg-mapped pixel formats are supported (usual ones like RGB(A), UYVY). Additionally v210, R10k and R12L is supported (but conversion to compatible FFmpeg formats is necessary, which can be potentially slow).

    b. for known _compressed_ containers (like _MP4_, _MKV_), default container video and audio compressed codec is used (just like if it would be processed with _ffmpeg_ command: `ffmpeg -i <input> out.mp4`), also 8-bit 4:2:0 YUV is configured for the video compression.

2. A/V is synchronized implicitly (as it is usual in UltraGrid). If it starts being unsynced, video frame is either dropped or dupped. The frame insertion or deletion is currently done if the difference is 1 video frame time - this may be too restrictive in some use cases (but can be tweaked).

Output file name can be of course a FIFO, if muxer supports non-seekable file.

**Comment by mikekoetter** [comment]
I'm doing some testing on this - would you like feedback in this thread?

**Comment by MartinPulec** [comment]
That would be great, feel free also to reopen if needed. I've just closed the thread to let know that we are not doing anything more at the time.

**Comment by mikekoetter** [comment]
I'm not sure the  max_av_diff option is working... also not sure the default 1.0 is working either.
I'm continuing to get these desync errors that are well below 1.0
`[File disp.] A-V desync 0.051507 sec, video frame dropped... 
`
It's a little hard to reproduce but I'll try to get some more specific reproducible information

**Comment by mikekoetter** [comment]
oh wait - I think maybe I am misinterpreting the argument here.  I (mistakenly) understood the  max_av_diff value to be a float value in seconds, as it is represented in the error.  Is it actually in frames?  Where the error above is representing a delta of 1.236168 frames ( hence greater than the 1.0 default) ?

**Comment by MartinPulec** [comment]
> Is it actually in frames? 

yes

I've just changed it to seconds to correspond with the warning.

It is also increased it to 0.084 s (84 ms; ~2 24p frames) to better fit eventual timing jitter (most likely due to video compression). I don't know your use case but I believe that it may have been due to this.

Just a small explanation – when writing to the output, a timestamp is assigned to the output, but it is (currently) made up by UG to avoid continuously increasing desync if audio and video is not properly synchronized (it mimics UG normal behavior - the frames are presented as soon as possible, so AV is synchronized implicitly).

**Comment by txtpauld** [comment]
Hey Martin!  I am coming back around to this to try and stream larger video formats through it.  I am currently trying to write out dual stream 3D UHD 24 10 bit 422 from a decklink 8k pro to the nut file and I am only about to get about ~15fps with lots of dropped frames.

`[DeckLink capture] 71 frames in 5.01418 seconds = 14.1598 FPS`

I am assuming that the data rates are probably higher than the system can handle for uncompressed video.  But I have used ultragrid to stream successfully stream dual stream 3D UHD 24 10 bit 422 and compress it via comprimato so I believe it is at least possible.  I have also done 48fps at the same resolution in 3D as well without trouble.  

I was wondering if it would be possible to use something like cineform as an intermediary compression format.  It looks like ffmpeg natively supports cineform in the nut container and ultragrid supports it as well.  Do you think something like this would be feasible?  

I am trying to avoid comprimato in this case because it's much harder to compress and I can spend the extra data since I am writing to a fifo and not sending it over the network.

And as a side test, I tried to run ultragrid while using the dummy output and I got a similar result of about 15fps:
```
uv -t decklink:device=0:mode=4k24:codec=v210:keep-settings:3D -M 3D   -d dummy
UltraGrid 1.10.3 (tags/v1.10.3^0 rev 12e27052b built Apr 17 2026 00:09:34)

Display device   : dummy
Capture device   : decklink
Audio capture    : none
Audio playback   : none
MTU              : 9000 B
Video compression: none
Audio codec      : PCM
Network protocol : UltraGrid RTP
Audio FEC        : none
Video FEC        : none

[DeckLink capture] Using codec: v210
[DeckLink capture] Using device DeckLink 8K Pro (1)
The desired display mode is supported: 2160p24
[DeckLink capture] Enable video input: 2160p24 (stereoscopic 3D)
[DeckLink capture] Video Colorspace: Rec.709
[DeckLink capture] Video Dynamic Range: SDR
Control socket listening on port 43889
[Pbuf] [video] 128/128 packets received (100.0000%), 0 lost, max loss 0
[video dec.] New incoming video format detected: 2*3840x2160 @24.00p, codec v210
[display] Successfully reconfigured display to 7680x2160 @24.00p, codec v210
[dummy] 77 frames in 5.03047 seconds = 15.3067 FPS
[DeckLink capture] 80 frames in 5.04598 seconds = 15.8542 FPS
[Pbuf] [video] 621342/699520 packets received (88.8241%), 78178 lost, max loss 7917
[dummy] 77 frames in 5.0298 seconds = 15.3088 FPS
[DeckLink capture] 77 frames in 5.02844 seconds = 15.3129 FPS
[Pbuf] [video] 665344/665344 packets received (100.0000%), 0 lost, max loss 0
[dummy] 79 frames in 5.05524 seconds = 15.6274 FPS
[DeckLink capture] 79 frames in 5.05725 seconds = 15.6211 FPS
[Pbuf] [video] 682496/682496 packets received (100.0000%), 0 lost, max loss 0
Video dec stats (cumulative): 242 total / 242 disp / 0 drop / 17 corr / 0 miss
Pbuf: total 5066782738/5438518144 packets received (93.16477%).
```

And here is a quick run writing out via the network with cineform:
```
uv -t decklink:device=0:mode=4k24:codec=v210:keep-settings:3D -M 3D -c cineform -P 7000 localhost
UltraGrid 1.10.3 (tags/v1.10.3^0 rev 12e27052b built Apr 17 2026 00:09:34)

Display device   : none
Capture device   : decklink
Audio capture    : none
Audio playback   : none
MTU              : 1500 B
Video compression: cineform
Audio codec      : PCM
Network protocol : UltraGrid RTP
Audio FEC        : none
Video FEC        : none

[DeckLink capture] Using codec: v210
[DeckLink capture] Using device DeckLink 8K Pro (1)
The desired display mode is supported: 2160p24
[DeckLink capture] Enable video input: 2160p24 (stereoscopic 3D)
[DeckLink capture] Video Colorspace: Rec.709
[DeckLink capture] Video Dynamic Range: SDR
[cineform] Threads: 8.
Control socket listening on port 36345
[cineform] Threads: 8.
[cineform] Start encoder pool
    Last message repeated 1 times
[DeckLink capture] 118 frames in 5.03813 seconds = 23.4214 FPS
[DeckLink capture] 120 frames in 5.00018 seconds = 23.9991 FPS
[DeckLink capture] 120 frames in 5.00028 seconds = 23.9986 FPS
[DeckLink capture] 120 frames in 5.00034 seconds = 23.9984 FPS
[DeckLink capture] 120 frames in 5.00025 seconds = 23.9988 FPS
Exit
```

Let me know is there are any other data points that could be helpful!  Thank you very much!

**Comment by txtpauld** [comment]
I ran one more test encoding dual stream 3D at 1080p24 as another data point through the nut fifo without issue
```
uv -t decklink:device=0:mode=24ps:codec=v210:keep-settings:3D -M 3D -s embedded --audio-capture-format channels=2 -r embedded -d file:file=/var/tmp/uv-decklink-1.nut:max_av_diff=1
UltraGrid 1.10.3 (tags/v1.10.3^0 rev 12e27052b built Apr 17 2026 00:09:34)

Display device   : file
Capture device   : decklink
Audio capture    : embedded
Audio playback   : embedded
MTU              : 9000 B
Video compression: none
Audio codec      : PCM
Network protocol : UltraGrid RTP
Audio FEC        : none
Video FEC        : none

[DeckLink capture] Using codec: v210
[DeckLink capture] Using device DeckLink 8K Pro (1)
The desired display mode is supported: 1080p24
[DeckLink capture] Enable video input: 1080p24 (stereoscopic 3D)
[DeckLink capture] Audio input set to: embedded
[DeckLink capture] Video Colorspace: Rec.709
[DeckLink capture] Video Dynamic Range: SDR
Audio receiving started.
Audio sending started.
Control socket listening on port 40709
[Pbuf] [video] 128/128 packets received (100.0000%), 0 lost, max loss 0
New incoming audio format detected: 48000 Hz, 2 channels, 32 bits per sample, codec PCM
Audio reconfiguration succeeded (2 channels, 4 Bps, 48000 Hz, codec: PCM).
[File disp.] Waiting for all streams to init.
    Last message repeated 1 times
[video dec.] New incoming video format detected: 2*1920x1080 @24.00p, codec v210
[display] Successfully reconfigured display to 3840x1080 @24.00p, codec v210
[lavc] Output #0, nut, to '/var/tmp/uv-decklink-1.nut':
[lavc]   Stream #0:0: Video: rawvideo (Y3[10][10] / 0xA0A3359), yuv422p10le, 3840x1080, q=2-31, 1990656 kb/s, 24 tbn
[lavc]   Stream #0:1: Audio: pcm_s32le, 48000 Hz, stereo, s32, 3072 kb/s
[Audio sender] Sent 148000 samples in last 5.02 seconds.
[Audio sender] Volume: [0] -inf/-inf, [1] -inf/-inf dBFS RMS/peak
[Pbuf] [audio] 128/128 packets received (100.0000%), 0 lost, max loss 0
[File disp.] 117 frames in 5.02625 seconds = 23.2778 FPS
[DeckLink capture] 120 frames in 5.02229 seconds = 23.8935 FPS
[audio dec.] Received 1936000/1936000 B, decoded 242000 samples in 5.03 sec.
[audio dec.] Volume: [0] -inf/-inf, [1] -inf/-inf dBFS RMS/peak
[Pbuf] [video] 257943/261120 packets received (98.7833%), 3177 lost, max loss 1500
[Audio sender] Sent 240000 samples in last 5.00 seconds.
[Audio sender] Volume: [0] -inf/-inf, [1] -inf/-inf dBFS RMS/peak
[Pbuf] [audio] 128/128 packets received (100.0000%), 0 lost, max loss 0
[File disp.] 120 frames in 5.00042 seconds = 23.998 FPS
[DeckLink capture] 120 frames in 5.00023 seconds = 23.9989 FPS
[audio dec.] Received 1920000/1920000 B, decoded 240000 samples in 5.00 sec.
[audio dec.] Volume: [0] -inf/-inf, [1] -inf/-inf dBFS RMS/peak
[Pbuf] [video] 261376/261376 packets received (100.0000%), 0 lost, max loss 0
[Audio sender] Sent 242000 samples in last 5.04 seconds.
[Audio sender] Volume: [0] -inf/-inf, [1] -inf/-inf dBFS RMS/peak
[Pbuf] [audio] 256/256 packets received (100.0000%), 0 lost, max loss 0
Played 638,000 audio samples in 15.37 seconds (41512.761528 samples per second).
Audio dec stats (cumulative): 318 played / 318 total audio frames
Pbuf: total 640/640 packets received (100.00000%).
Video dec stats (cumulative): 319 total / 319 disp / 0 drop / 2 corr / 0 miss
Pbuf: total 636944904/643284608 packets received (99.01448%).
Exit
```
