### ISSUE TITLE
Add Intel SVT encoders to UV.

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#34]
Hello,

I'd be interested in having the Intel SVT encoders added to UV.  There is a large performance increase with these encoders.  They are only YUV currently, but they do support 10bit, not sure about 12bit.  There would have to be a (sdi)RGB->YUV (full range)->RGB(sdi) applied.

While I would prefer to stay native RGB the whole way, getting hardware fast enough to do 2048x1080 10bit RGB x265 has proven difficult.  Not sure how much color precision would be lost in the RGB/YUV conversion.

**Comment by MartinPulec** [comment]
Thanks for the idea, I've quickly looked at an implementation for FFMPEG ([here](https://github.com/OpenVisualCloud/SVT-AV1/tree/master/ffmpeg_plugin) and [here](https://github.com/OpenVisualCloud/SVT-HEVC/tree/master/ffmpeg_plugin), not merged in upstream) and it didn't looked too much complex. For now it should be possible to use the codec through that implementation.

I am not sure whether not wait a bit if the implementation won't get upstream to FFMPEG.

**Comment by alatteri** [comment]
I think you have added this in recent builds.  I'm closing.
