### ISSUE TITLE
[DeckLink] clicking in audio with 24 FPS in sync mode

### ISSUE THREAD

**Issue by MartinPulec** [CESNET/UltraGrid#345]
_Originally posted by @alatteri in https://github.com/CESNET/UltraGrid/issues/326#issuecomment-1757020332_

Clicks in audio are present if using audio compression with 24 FPS. Steps to reproduce:

    ffmpeg -f lavfi -i sine=r=48000:d=30 -f lavfi -i testsrc=duration=30:r=24:size=1920x1080 tst24.mp4
    uv -d decklink:sync -r embedded -t file:tst24.mp4 -s embedded --param incompatible -A AAC

Occurs also with _OPUS_. **Doesn't** occur if anything of following holds:
1. synchronized mode is **not** use
2. **PCM** (uncompressed) audio is used
3. 25 **FPS** is used (other frame rates not tested)

**Comment by MartinPulec** [comment]
reproducible also simply with `-t testcard:mode=Hp24 -s embedded`

**Comment by alatteri** [comment]
Thanks for looking into this.  Do you think it is fixable?   Having to send un-compressed PCM with sync mode is not ideal, but it is better than un-syncronized V/A.

**Comment by MartinPulec** [comment]
Well, I've slightly ill-designed the new audio compression code while perhaps too much complicating it. I've just simplified it by properly time-stamping the compressed audio.

It is already pushed it but not much tested – just the simple use-cases, where it seem to work. Hopefully I'll get to some more testing in following days.

**Comment by MartinPulec** [comment]
I've just fixed a small bug (8e8c1f33) that sometimes triggered incorrect behavior (on incommensurable codec and input frame sizes and when audio BPS doesn't much compression, which 4 for AAC, so eg. testcard's 2)

**Comment by alatteri** [comment]
I believe this is now fixed in latest continuous.  Test with both AAC and OPUS.

Thank you.
