### ISSUE TITLE
Spout crashing on SPOUTLIBRARY::SetSpoutLogLevel()

### ISSUE THREAD

**Issue by MartinPulec** [CESNET/UltraGrid#352]
_Originally posted by @zbynekdrlik in https://github.com/CESNET/UltraGrid/issues/348#issuecomment-1783558388_

UltraGrid crashes when setting log level (both capture and display part) with following stacktrace (`uv -t spout`):
```
#0  0x00007ffffa771a77 in ucrtbase!_wtol () from C:\WINDOWS\System32\ucrtbase.dll
#1  0x00007ffffa772304 in ucrtbase!_wctomb_s_l () from C:\WINDOWS\System32\ucrtbase.dll
#2  0x00007ffffa772ed1 in ucrtbase!.stdio_common_vsprintf_s () from C:\WINDOWS\System32\ucrtbase.dll
#3  0x00007fffdc2e5c4f in SpoutLibrary!?_doLog@spoututils@@YAXW4SpoutLogLevel@1@PEBDPEAD@Z ()
   from C:\tools\msys64\home\toor\ultragrid-devel\bin\SpoutLibrary.dll
#4  0x00007fffdc2e26d2 in SpoutLibrary!??4spoutSenderNames@@QEAAAEAV0@AEBV0@@Z ()
   from C:\tools\msys64\home\toor\ultragrid-devel\bin\SpoutLibrary.dll
#5  0x00007ff6acc367cf in vidcap_spout_init (params=<optimized out>, state=0x41043ea0) at src/video_capture/spout.cpp:190
#6  0x00007ff6acba6c5d in initialize_video_capture (parent=0x14fb50, param=0x487d20, state=0x14fb38) at src/video_capture.cpp:158
#7  0x00007ff6accc573a in main (argc=3, argv=0x4d3cf0) at src/main.cpp:1403
```

reproducible in continuous (5ac3f93), [1.8.6](https://github.com/CESNET/UltraGrid/releases/tag/v1.8.6), [1.8.5](https://github.com/CESNET/UltraGrid/releases/tag/v1.8.5) **but** not in [1.8.4](https://github.com/CESNET/UltraGrid/releases/tag/v1.8.4) and below.

**Comment by zbynekdrlik** [comment]
Ready for testing fixes :)

**Comment by MartinPulec** [comment]
> Ready for testing fixes :)

Already built [here](https://github.com/CESNET/UltraGrid/releases/tag/continuous). I've just waited for the build to be finished [before reporting](https://github.com/CESNET/UltraGrid/issues/348#issuecomment-1784865947_) – it takes some half an hour.

**Comment by MartinPulec** [comment]
It looks like the issue is caused by the Spout [pre-built library](https://github.com/leadedge/Spout2/blob/master/BUILD/Binaries/x64/SpoutLibrary.dll) (version 2.007.0**10**) no longer being compatible with the Spout headers in Git (version 2.007.0**12**). When the library is built from sources in the Git, the problem no longer occurs. If this is correct, also other problems may occur.

Anyways, the libraries are not expected to be included in the repository in future as indicated in leadedge/Spout2#103.
