### ISSUE TITLE
Question: How to have more than one x265 param??

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#36]
Hello,

In doing H.265 performance testing, I am settings different x265 parameter like this:
`libavcodec:codec=H.265:x265-params=pme:bitrate=20M`

But I've been unable to figure out how to set more than a single x265 parameter at a time.
Can you please give me some guidance.

Thanks,
Alan

**Comment by MartinPulec** [comment]
You mean more than one parameter to x264-params? With current UltraGrid version, you may be able to escape the colon:
`uv -t <capture> -c 'libavcodec:encoder=libx265:x265-params=a=b\:x=y'`

Here both parameters _a_ and _x_ are passed to the codec as _x265-params_.

**Comment by alatteri** [comment]
Yes, that is what I was asking.  I will try it.  Thanks.

**Comment by alatteri** [comment]
Confirmed.  Using `x265-params=a=b\:x=y` allows multiple parameters to be specified.
