### ISSUE TITLE
Increase max audio bitrate

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#37]
Hello.

It would be helpful to increase the max audio bitrates for AAC/OPUS past 256k.  With SDI capture having 8/16 channels, 256K is not a lot of data to allow a high quality audio signal.

**Comment by MartinPulec** [comment]
Hi Alan, AFAIK the bitrate is given per channel - I'll make it clear in documentation. Or do you encounter some low quality with higher number of channels? If so, it may be caused by something else.

Another remark is that UltraGrid doesn't explicitly limit audio bitrate anyhow – it is just passed to the codec as user specified (at least should be).

**Comment by alatteri** [comment]
Thank you for the clarification.  I thought the bitrate was overall.  I haven't experienced quality problem, but it was something I was thinking about.

**Comment by MartinPulec** [comment]
Sure, thanks for pointing out – the truth is that it is not clear at all.

**Comment by alatteri** [comment]
In reviewing the FFmpeg wiki and man pages, there is no indication the the bitrate is per channel.  Everything seems to point to overall bitrate.

> As a rule of thumb, for audible transparency, use 64 kBit/s for each channel (so 128 kBit/s for stereo, 384 kBit/s for 5.1 surround sound).

If I remember correctly, the max bitrate UV allows is 256.

**Comment by MartinPulec** [comment]
That is not entirely correct – UltraGrid encodes the audio per channel (non-interleaved) so it never encodes more than one channel with FFMPEG. If there is more channels, it opens multiple FFMPEG instances.

Secondly, can you think over where have you seen the limitation to 256 kbps? I mean I am not aware of such a limit but it may arise from something which I don't realize.

**Comment by MartinPulec** [comment]
I've tested that MP3 and AAC support 512k (didn't tested more). OPUS doesn't but that is intrinsic to the codec (or implementation in FFPEG).

**Comment by alatteri** [comment]
Thanks Martin.  Sorry I didn't get a chance to test that.  But OPUS must have been what I was thinking.  Didn't realize that was just a codec limitation.  I'm closing the issue.
