### ISSUE TITLE
FEC with audio

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#38]
Currently only Video can have FEC.  Audio must be sent in multiples to have some level of error correction.  With 8/16 channels of audio at a high bitrate, this additional 2 or 3x multiple of audio can start to add significant amount of data to the stream.  Why was FEC excluded from audio, and can it be added?  Would it make sense to packetize the video and audio together and then do an overall FEC?  Thanks.

**Comment by MartinPulec** [comment]
Well, I've quickly computed that 16 channels at 256 kbps occupy divided 24 per second (24 frames per second) take approximately 15 standard Ethernet packets – this is unusable for LDGM but could be used for Reed-Solomon. However, it is quite extreme case, usually one audio frame takes up one to few packets. On the other hand, it is definitely worth considering.

Interleaved audio+video doesn't seem to be a solution to me. It has some other advantages, like implicit synchronization but I don't think that from the FEC perspective. It is rather question of attitude - I guess that MPEG-TS does that but within UltraGrid audio and video are more independent.

**Comment by alatteri** [comment]
Hi Martin... Thank you for the follow up.  In my use case scenario I would be using H264/265, so RS is the FEC schema I'd be using anyway.

Please correct me if I am wrong, but assuming a bitrate of 256000 bits/s is used for the audio, 16* 256000=4.096megabits/s (0.512MegaBytes/s).  Now if we 3x that stream for redundancy, we are at 12.288megabits/s (1.536MegaBytes/s).  Since H.265 can produce high quality streams at ~30megabits/s (3.75MB/s) and H.264 ~50megabits/s (6.25MB/s), the audio would be between 25-40% of the data load.  It is not a huge problem, but something I've been thinking about.  Seems wasteful to triplicate data, but easily doable with modern WAN speeds.

**Comment by MartinPulec** [comment]
Hi Alan, no no, I agree, in this case it surely makes sense. It is just it requires some implementation effort.
