### ISSUE TITLE
Is Cuneiform no longer supported?

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#391]
./UltraGrid.AppImage  -c libavcodec:help 
UltraGrid 1.9+ (master rev 97e41d4 built May 16 2024 08:02:50)

Supported codecs:
	H.264 - available (encoders: libx264 libx264rgb h264_nvenc h264_qsv h264_v4l2m2m h264_vaapi; decoders: h264 h264_v4l2m2m h264_qsv h264_cuvid)
	H.265 - available (encoders: libx265 libsvt_hevc hevc_nvenc hevc_qsv hevc_v4l2m2m hevc_vaapi; decoders: hevc hevc_qsv hevc_v4l2m2m libde265 hevc_cuvid)
	MJPEG - available (encoders: mjpeg mjpeg_qsv mjpeg_vaapi; decoders: mjpeg mjpeg_cuvid mjpeg_qsv)
	VP8 - available (encoders: libvpx vp8_v4l2m2m vp8_vaapi; decoders: vp8 vp8_v4l2m2m libvpx vp8_cuvid vp8_qsv)
	VP9 - available (encoders: libvpx-vp9 libsvt_vp9 vp9_vaapi vp9_qsv; decoders: vp9 vp9_v4l2m2m libvpx-vp9 vp9_cuvid vp9_qsv)
	J2K - available (encoders: jpeg2000; decoders: jpeg2000)
	HFYU - available (encoders: huffyuv; decoders: huffyuv)
	FFV1 - available (encoders: ffv1; decoders: ffv1)
	AV1 - available (encoders: libaom-av1 librav1e libsvtav1 av1_nvenc av1_qsv; decoders: libdav1d libaom-av1 av1 av1_cuvid av1_qsv)
	PRORES - available (encoders: prores prores_aw prores_ks; decoders: prores)

I also tried building it myself, using the proper steps, and even though autogen showed Cuneiform : yes it doesn't com up in the encoder list.

**Comment by mpiatka** [comment]
Cineform is not implemented through libavcodec, but is rather implemented as a standalone codec. As such it will show up in `uv -c help` rather than `uv -c libavcodec:help`.

I tested the latest continuous build and `./UltraGrid-continuous-x86_64.AppImage -t testcard -c cineform` seems to work without any problems.

**Comment by alatteri** [comment]
thank you.  it's been a while since I tested Cineform.
