### ISSUE TITLE
Spout not working

### ISSUE THREAD

**Issue by zbynekdrlik** [CESNET/UltraGrid#402]
Hi, spout input device is not working in 1.9.4 and also in nightly build.

**Comment by MartinPulec** [comment]
Do you have any further details how to reproduce the problem? It doesn't seem to be generic - I've downloaded [Spout build](https://github.com/leadedge/Spout2/releases/download/v2.005/SPOUT_2007-014.zip), run _DEMO/SpoutSender.exe_ from it and UltraGrid was able to capture it without problems (both versions), using:
```
.\uv.exe -t spout -d gl
```

**Comment by zbynekdrlik** [comment]
I am using it with obs as sender. 

![image](https://github.com/user-attachments/assets/089db658-7c83-470f-924f-e385d8dc7258)


I have also test this on my laptop and there it is correctly working. What else could I do to debug it?

**Comment by zbynekdrlik** [comment]
And this is list of spout displays on related not working computer
![image](https://github.com/user-attachments/assets/33e9c5f5-143e-4be5-bfef-c1e9a9386c10)

**Comment by MartinPulec** [comment]
Sorry for the delayed response - I've missed your response somehow.

Unfortunately, I still cannot reproduce the problem - as indicated above, the sample Spout sender worked flawlessly for me. Also the signal generated by UltraGrid itself - `uv -t testcard -d spout` can be normally captured.

Would it be possible to try these 2 senders to check if there is some general problem with Spout or is it specific to some sender(s) only? If the second is true, what is the actual program(s) that acts as the Spout sender that is UltraGrid incapable to capture?
