### ISSUE TITLE
DRM Display Device missing on Linux Build 

### ISSUE THREAD

**Issue by jonathan-catt** [CESNET/UltraGrid#412]
Hello, 

I am hoping to build a headless UG receiver "set top box" using the DRM display device on a Intel N100 based mini PC. The device has two HDMI ports (which we plan to use one) and based on the QSV spec should support up to HEVC 12bit 444. The idea behind using the DRM display is to not need to boot up to a graphical target first before UG launches. As I understand it the DRM device would also force the output format to match the encoded format for bitdepth, color sampling and frame rate, therefor minimizing artifacts around vertical blanking and sync. However with the latest 1.9.6 build I did not find a DRM display device as an option. Is this only supported on the ARM build? and if so would it be possible to support in x86_64 build as well?

```
UltraGrid 1.9.6 (tags/v1.9.6 rev ccd9026 built Aug 28 2024 10:32:08)

Available display devices:
        aja
        caca
        decklink
        dummy
        dump
        file
        gl
        ndi
        pano_gl
        pipewire
        sdl
        v4l2
        vulkan_sdl2
(use "fullhelp" to show hidden displays)
```

```
Trying display: drm
libva info: VA-API version 1.18.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_18
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.18 (libva 2.18.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 23.2.1 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileNone                   : VAEntrypointStats
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Simple            : VAEntrypointEncSlice
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointFEI
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointFEI
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointFEI
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointFEI
      VAProfileHEVCMain               : VAEntrypointEncSliceLP
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointEncSliceLP
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointEncSliceLP
      VAProfileVP9Profile1            : VAEntrypointVLD
      VAProfileVP9Profile1            : VAEntrypointEncSliceLP
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointEncSliceLP
      VAProfileVP9Profile3            : VAEntrypointVLD
      VAProfileVP9Profile3            : VAEntrypointEncSliceLP
      VAProfileHEVCMain12             : VAEntrypointVLD
      VAProfileHEVCMain12             : VAEntrypointEncSlice
      VAProfileHEVCMain422_10         : VAEntrypointVLD
      VAProfileHEVCMain422_10         : VAEntrypointEncSlice
      VAProfileHEVCMain422_12         : VAEntrypointVLD
      VAProfileHEVCMain422_12         : VAEntrypointEncSlice
      VAProfileHEVCMain444            : VAEntrypointVLD
      VAProfileHEVCMain444            : VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         : VAEntrypointVLD
      VAProfileHEVCMain444_10         : VAEntrypointEncSliceLP
      VAProfileHEVCMain444_12         : VAEntrypointVLD
      VAProfileHEVCSccMain            : VAEntrypointVLD
      VAProfileHEVCSccMain            : VAEntrypointEncSliceLP
      VAProfileHEVCSccMain10          : VAEntrypointVLD
      VAProfileHEVCSccMain10          : VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444         : VAEntrypointVLD
      VAProfileHEVCSccMain444         : VAEntrypointEncSliceLP
      VAProfileAV1Profile0            : VAEntrypointVLD
      VAProfileHEVCSccMain444_10      : VAEntrypointVLD
      VAProfileHEVCSccMain444_10      : VAEntrypointEncSliceLP
```

**Comment by alatteri** [comment]
QSV is not color accurate.  See https://github.com/CESNET/UltraGrid/issues/341

We created a similar Ubuntu using LightDM to create an appliance expirience, based off Intel NUCs.

**Comment by MartinPulec** [comment]
Hi,

> However with the latest 1.9.6 build I did not find a DRM display device as an option.

That seems valid - the DRM display was added in April 2024, UltraGrid 1.9 was released in February. The point releases (1.9.1, 1.9.2...) are just bug-fix releases, new features from the development are usually not added. You can use the Git version (or continuous builds build from it [here](https://github.com/CESNET/UltraGrid/releases/tag/continuous)).

> Is this only supported on the ARM build?

Well, stable releases are not (yet) built for Linux ARMs, just the [continuous](https://github.com/CESNET/UltraGrid/releases/tag/continuous) version. As indicated above, DRM should be built for x86_64 in the continuous as well.

**Comment by mpiatka** [comment]
Hello,

the DRM display was added mainly to support zero-copy presentation of hw. decoded frames on the Raspberry Pi 4, which is too underpowered for the GL display.

Right now it's also pretty barebones and lacking support for any kind of scaling and currently also no vsync. The N100 is plenty powerful, so I would suggest running some minimal Wayland or X11 environment and use the gl display with the ``:fs`` parameter to make it start fullscreen instead.

**Comment by MartinPulec** [comment]
Just FYI, I've just tried (and fixed) a KMS mode of UltraGrid SDL2 display. So you can now also use **SDL2** with **KMSDRM** backend for headless setups like this:

    uv -t testcard -d sdl:driver=KMSDRM

**Comment by alatteri** [comment]
1) Does running sdl:driver=KMSDRM have any performance benefit over vulkan_sdl2 in a minimal X11 environment?
2) does sdl:driver=KMSDRM support 10bit color like vulkan_sdl2 does?

**Comment by MartinPulec** [comment]
> 1. Does running sdl:driver=KMSDRM have any performance benefit over vulkan_sdl2 in a minimal X11 environment?

I would not expect it but it is hard to tell in general. Also a question is how to measure the performance, whether the latency, the throughput in MPix/s or something else. Anyways, I didn't think it as a alternative for X11/Wayland SW displays, but rather when the desktop env is unavailable or undesired.
 
>  2. does sdl:driver=KMSDRM support 10bit color like vulkan_sdl2 does?

yes/no/it depends:

**yes** -  from 10-bit formats only **R10k** (thus 10-bit RGB) is supported. However, it has not been enabled by default until now (it didn't seem to work in the past - now it seem to behave correctly). As far as I know, **SDL** should abstract different backends so it shouldn't matter if the driver is _X11_ or _KMSDRM_.

**no** - it doesn't support all the pixel formats as vulkan_sdl2 does, namely 10-bit YCbCr or RG48 are not supported

**Comment by alatteri** [comment]
OK...thanks.  I'll stick with my current LightDM/vulkan_sdl2 implementation which is more flexible.

> **no** - it doesn't support all the pixel formats as vulkan_sdl2 does, namely 10-bit YCbCr or RG48 are not supported

**Comment by jonathan-catt** [comment]
Thanks Alan and Martin, you both have been very helpful. Conceptually we are thinking of using NVENC to perform encodes and use the Intel N100 for decodes only, have you found that the same color accuracy issues are present with the decoder? or just the encoder?

I can put in another request/issue for this, but would JPEG XS be a better format over HEVC then to provide color accurate video in a "headless" style appliance? I noticed Intel have published their library for JPEG XS that supports YUV up to 444 14-bit and RGB up to 14bit: https://github.com/OpenVisualCloud/SVT-JPEG-XS

**Comment by alatteri** [comment]
@jonathan-catt   Start a new discussion (not issue) and close this one out as I think @MartinPulec has addressed the original issue.  Happy to discuss the other stuff in a new thread.

**Comment by alatteri** [comment]
Might be relevant to this issue.

https://www.phoronix.com/news/FFmpeg-Vulkan-Implicit-Sync
