### ISSUE TITLE
Wrong buffer size in import capture

### ISSUE THREAD

**Issue by asergunov** [CESNET/UltraGrid#42]
https://github.com/CESNET/UltraGrid/blob/c77fd4f1001dff53ee56252f37d1e95564f60610/src/video_capture/import.cpp#L356-L359

**Comment by asergunov** [comment]
`sizeof("/soud.wav") ` but `strcat(audio_filename, "/sound.wav");`

**Comment by mliska** [comment]
Hi Anton, 
thanks for pointing this out. Fixed in https://github.com/CESNET/UltraGrid/commit/0f6767b201d2f3f962e42cce135671405abd312a.
Milos
