### ISSUE TITLE
windows binary with NDI support?

### ISSUE THREAD

**Issue by michaelpalumbo** [CESNET/UltraGrid#43]
Hi There,

I'm wondering if there is a windows binary available with native NDI support? thanks!

**Comment by MartinPulec** [comment]
Hi Michael,

actually no, mostly due to licensing reasons. I am not sure if there is any update on that. But you may be able to build it by yourself. If you do not want to set the build environment, you may try to use fork [this branch](../../../MartinPulec/UltraGrid/tree/ci) and use the prepared C/C++ CI workflow. I'd need:
- modify `.github/scripts/Windows/prepare.ps1` - install NDI, please use default installation location (as you can se in the example)
- in workflow file (`.github/workflows/ccpp.yml`) remove `--disable-ndi` and remove restriction on repository for Windows job
- optionally modify the "Upload build" step

Let me know if it doesn't work or there is a problem with the workflow.

Martin

**Comment by michaelpalumbo** [comment]
Wow, thank you @MartinPulec 

Ok, so the powershell script threw the following error:

```shell
The term 'Invoke-WebRequest' is not recognized as the name of a cmdlet, function, script file, or operable program. Che
ck the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\user\ultragrid\.github\scripts\windows\prepare.ps1:14 char:20
+   Invoke-WebRequest <<<<  https://developer.download.nvidia.com/compute/cuda/10.2/Prod/local_installers/cuda_10.2.89_
441.22_win10.exe -OutFile cuda_inst.exe
    + CategoryInfo          : ObjectNotFound: (Invoke-WebRequest:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Start-Process : This command cannot be executed due to the error: The system cannot find the file specified.
At C:\Users\user\ultragrid\.github\scripts\windows\prepare.ps1:15 char:16
+   Start-Process <<<<  -FilePath "cuda_inst.exe" -ArgumentList "-s nvcc_10.2" -Wait -NoNewWindow
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

Remove-Item : Cannot find path 'C:\Users\user\ultragrid\.github\scripts\windows\cuda_inst.exe' because it does not exis
t.
At C:\Users\user\ultragrid\.github\scripts\windows\prepare.ps1:16 char:14
+   Remove-Item <<<<  cuda_inst.exe
    + CategoryInfo          : ObjectNotFound: (C:\Users\user\u...s\cuda_inst.exe:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

```

I'll note that i ran it two times, first with the msys install commented out as it'd already installed it last week, and the second ran with uncommented and added a --force flag. both times it exited with the above error.

**Comment by michaelpalumbo** [comment]
Is the ps1 necessary, though? I've already installed ndi via the packages on their website (both ndi, ndi tools, and the sdk)

**Comment by michaelpalumbo** [comment]
also, i don't know what this means:

> remove restriction on repository for Windows job

**Comment by MartinPulec** [comment]
> Is the ps1 necessary, though? I've already installed ndi via the packages on their website (both ndi, ndi tools, and the sdk), and our system has cuda installed (the ultragrid precompiled binary was working last week )

No, If you are not using the workflow to build it on the GitHub but you are building it locally on your machine, it is not certainly needed.

**Comment by MartinPulec** [comment]
> also, i don't know what this means:
> 
> > remove restriction on repository for Windows job

Similarly as above – if you don't run the job on GitHub runner, it is irrelevant. Just FYI, I meant [this line](https://github.com/MartinPulec/UltraGrid/blob/ci/.github/workflows/ccpp.yml#L100).
