### ISSUE TITLE
ultragrid build not detecting NDI on mac

### ISSUE THREAD

**Issue by michaelpalumbo** [CESNET/UltraGrid#45]
In the wiki, when compiling with NDI support, the guide says that following the steps will allow ultragrid to detect NDI:

https://github.com/CESNET/UltraGrid/wiki/Compile-UltraGrid-%28Source%29#NDI

However, when I run ./configure the result displays 

```shell
# rest of stdout ommitted
Video:
  AJA ......................... no    AV Foundation ............... yes
  BitFlow ..................... no    Bluefish444 (audio: no) ..... no
  DeckLink .................... yes   DELTACAST ................... no
  DirectShow .................. no    DVS ......................... no
  File input .................. no    NDI ......................... no
  OpenGL ...................... yes   QuickTime ................... no
  RTSP capture client ......... no    SAGE ........................ no
  Screen capture .............. yes   SDL (ver. 1) ................ no
  SW video mix ................ yes   V4L2 ........................ no
  XIMEA ....................... no
``` 

where, NDI is not set to 'YES'

**Comment by MartinPulec** [comment]
It most likely didn't detect either headers or the library itself. Would it be possible to attach generated config.log and also the environment variables CPATH, LIBRARY_PATH and DYLD_LIBRARY_PATH.

I've also modified the instructions you linked (now it reflects different installation location of NDI 4 and doesn't suggest renaming but rather symlinking) so you may also recheck if everything is correct.
