### ISSUE TITLE
control port API

### ISSUE THREAD

**Issue by michaelpalumbo** [CESNET/UltraGrid#46]
Hi, this feature is compelling, thanks for including it!

It's not clear to me what protocol I should use (OSC, unformatted UDP, websockets), could you clarify this?

Once I can get this working, I'd be glad to contribute a nodejs client for controlling ultragrid

**Comment by michaelpalumbo** [comment]
Hi @MartinPulec Would love to get this topic going :)

**Comment by MartinPulec** [comment]
Well, it is a command-like plain-text syntax sent over plain TCP (UltraGrid is server, but has also a client mode). Implicitly it is restricted to a local connections, but with `--param control-accept-global`, user can make possible also remote control.

**Comment by llamafilm** [comment]
I'm not sure where these commands can be entered.  Can you share an example?

**Comment by MartinPulec** [comment]
> I'm not sure where these commands can be entered. Can you share an example?

    uv <params> --control-port 5054 --param control-accept-global

and then it is simple raw TCP socket, so `netcat <address> 5054`. But this is really not clear solution of the problem. Moreover the API is not public/official.
