### ISSUE TITLE
Decoder fails with SVT-HEVC

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#48]
Hello,

I've built all the Intel SVT modules, applied the ffmpeg-plugin patches and build ffmpeg from source, on latest Debian 10.3 on the receiver side.  Sender side I am using Ubuntu 19.10 and followed the same build process.

When sending with:
`uv -t testcard:1920:1080:24:RGB -c libavcodec:codec=H.265:encoder=libsvt_hevc 172.102.1.32`

Decoder is failing with: 
`[lavd]  Error while decoding frame (rc == -1094995529): Invalid data found when processing input.
[hevc @ 0x7efe24004900] PPS id out of range: 0
[hevc @ 0x7efe24004900] Error parsing NAL unit #0.
[lavd]  Error while decoding frame (rc == -1094995529): Invalid data found when processing input`

Full sender output:
```
UltraGrid 1.5+ (tags/continuous rev cc85548c built Apr  4 2020 16:02:36)

Display device   : none
Capture device   : testcard
Audio capture    : none
Audio playback   : none
MTU              : 1500 B
Video compression: libavcodec:codec=H.265:encoder=libsvt_hevc
Audio codec      : PCM
Network protocol : UltraGrid RTP
Audio FEC        : none
Video FEC        : none

Created new RTP session with SSRC 0x4df3ba99.
Display initialized-none
Fill rect at 0,0
Fill rect at 320,0
Fill rect at 640,0
Fill rect at 960,0
Fill rect at 1280,0
Fill rect at 1600,0
Fill rect at 0,320
Fill rect at 320,320
Fill rect at 640,320
Fill rect at 960,320
Fill rect at 1280,320
Fill rect at 1600,320
Fill rect at 0,640
Fill rect at 320,640
Fill rect at 640,640
Fill rect at 960,640
Fill rect at 1280,640
Fill rect at 1600,640
Fill rect at 0,960
Fill rect at 320,960
Fill rect at 640,960
Fill rect at 960,960
Fill rect at 1280,960
Fill rect at 1600,960
Testcard capture set to 1920x1080, bpp 3.000000
Video capture initialized-testcard
Created new RTP session with SSRC 0x6f383152.
[lavc] Using codec: H.265, encoder: libsvt_hevc
[lavc] Setting bitrate to 7962624 bps.
[lavc] Warning: Unknown encoder libsvt_hevc. Using default configuration values.
[lavc] Warning: Unable to find suitable preset for encoder libsvt_hevc.
SVT [version]:	SVT-HEVC Encoder Lib v1.4.3
SVT [build]  :	GCC 9.2.1 20191008	 64 bit
LIB Build date: Apr  4 2020 16:42:04
-------------------------------------------
Number of logical cores available: 6
Number of PPCS 53
------------------------------------------- 
SVT [config]: Main Profile	Tier (auto)	Level (auto)	
SVT [config]: EncoderMode / Tune							: 7 / 1 
SVT [config]: EncoderBitDepth / CompressedTenBitFormat / EncoderColorFormat 		: 8 / 0 / 1
SVT [config]: SourceWidth / SourceHeight / InterlacedVideo				: 1920 / 1080 / 0
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType 		: 24 / 1 / 20 / -1
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure			: 3 / 0 / 2 
SVT [config]: BRC Mode / QP / LookaheadDistance / SceneChange				: CQP / 32 / 17 / 1 
SVT [config]: BitRateReduction / ImproveSharpness					: 0 / 0 
SVT [config]: tileColumnCount / tileRowCount / tileSliceMode / Constraint MV 		: 1 / 1 / 0 / 0
SVT [config]: De-blocking Filter / SAO Filter						: 1 / 1 
SVT [config]: HME / UseDefaultHME							: 1 / 1 
SVT [config]: MV Search Area Width / Height 						: 16 / 7 
SVT [config]: HRD / VBV MaxRate / BufSize / BufInit					: 0 / 0 / 0 / 90
------------------------------------------- 

SVT [WARNING] Elevated privileges required to run with real-time policies! Check Linux Best Known Configuration in User Guide to run application in real-time without elevated privileges!

[lavc] Selected pixfmt: yuv420p
[capture] 117 frames in 5.03538 seconds = 23.2356 FPS
[capture] 120 frames in 5.00001 seconds = 24 FPS
[capture] 120 frames in 5 seconds = 24 FPS
[capture] 120 frames in 5.00023 seconds = 23.9989 FPS
[capture] 120 frames in 5.0002 seconds = 23.999 FPS
Exit

```

**Comment by MartinPulec** [comment]
Thanks for reporting, I was able to reproduce the problem on Ubuntu 18.04 (both sender and receiver).

**Comment by MartinPulec** [comment]
It seems that the problem was caused by the fact that the SVT HEVC/AV1 encoders produce open GOP by default. UltraGrid then don't catch first frame (even if so, it is discarded because of colorspace probe) and thus is unable to decode any of following frames.

I've pushed a fixes to the repo which seem to fix the problem. I am unsure about latency anyway - it looks like the encoder caches many frames (up to the whole GOP), which would have very negative impact on latency. This may need to be also tweaked then - feel free to let us know if you find out something about that.

**Comment by alatteri** [comment]
Thanks Martin.  I will try this weekend.
When using x265 encoder I can change parameter using `H.265:x265-params=`
Do you know what I should use for libsvt_hevc ?

**Comment by MartinPulec** [comment]
> When using x265 encoder I can change parameter using `x265-params=`
> Do you know what I should use for libsvt_hevc ?

I guess that there is no analogical option. Available ones are listed [here](https://github.com/OpenVisualCloud/SVT-HEVC/blob/6a9803dc03448513822538ebc0da21afc9685255/ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch#L518). The wrapper code can be modified of course.

**Comment by alatteri** [comment]
Hi Martin,

would I use `svt-hevc-params=`  ?  That is what I am now clear on, how to even instigate the special parameters.

**Comment by MartinPulec** [comment]
The available parameters are defined by [this structure](https://github.com/OpenVisualCloud/SVT-HEVC/blob/6a9803dc03448513822538ebc0da21afc9685255/Source/API/EbApi.h#L171) which is also set by the FFMPEG module. I am not sure if there is a possibility to serialize the parameters to a string like it is for x264/5. You may end up with picking the ones that are important individually.

**Comment by alatteri** [comment]
I was able to get SVT-HEVC working with self build of FFMPEG to enable that codec.  The quality was really poor though.  I'll need to explore the options some more.  Closing this issue since the bug is fixed.

**Comment by MartinPulec** [comment]
> I was able to get SVT-HEVC working with self build of FFMPEG to enable that codec. The quality was really poor though. I'll need to explore the options some more. Closing this issue since the bug is fixed.

I'd be glad if you let me know if you find some configuration that improve the behavior (ideally improve quality with acceptable impact on performance/latency). I'd then add it to UltraGrid (or you can create a merge request). Currently, SVT options are pretty default (except common parameters like GOP size, bitrate and specially for SVT `forced-idr=1`, which forces closed GOP).
