### ISSUE TITLE
need way to delay audio

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#51]
when using x265 with option frame-threads=N
The audio will be out of sync N frames
A possible solution would be to delay the audio N frames when frame-threads is used,  so that video/audio are in sync.

**Comment by alatteri** [comment]
actually I think the proper delay setting would be (N-1).

**Comment by MartinPulec** [comment]
Have you tried the option `--audio-delay <ms>`. IIRC positive values add the audio delay (in milliseconds). It should take negative values as well (to delay the video).

**Comment by alatteri** [comment]
I did not even know that existed.  Is it documented?   Sounds like exactly what I need.  Will test.

**Comment by alatteri** [comment]
Except this really needs to be on the sender.  Since that might be a dynamic value, or not at all, depending on the codec choice.  Having it on the player is cumbersome, since any change in the encoder settings, would need to be updated on N players.

So can this be added to the encoder?

**Comment by MartinPulec** [comment]
> I did not even know that existed. Is it documented?

Yes, somehow. At least in `--fullhelp`.

> Except this really needs to be on the sender. Since that might be a dynamic value, or not at all, depending on the codec choice. Having it on the player is cumbersome, since any change in the encoder settings, would need to be updated on N players.

I understand, this makes sense. 

> So can this be added to the encoder?

Yes, I think that this would be a useful feature. The only thing is that there is currently no infrastructure in UltraGrid for that (something like video capture filter) so it will take some time.

**Comment by TheSashmo** [comment]
Just pushing this back to the top.

Using the encoder I am not able to adjust any audio increase or delay.  Using the command line or the realtime <> options.  I am using Opus codec for my test and SDP protocol.  Could that be it?

I am able to adjust in the decoder for sure.  That I can confirm.

**Comment by mpiatka** [comment]
The nightly builds now contain a `delay` [audio filter](https://github.com/CESNET/UltraGrid/wiki/Audio-filters), that can be used to add audio delay on the sender. The delay can then be also controlled using the [control port.](https://github.com/CESNET/UltraGrid/wiki/Control-port-API#audio-filters-sender-only)

In short:
```
uv --audio-filter delay:2000 -s <capture_device>
```
Adds 2 seconds of delay.
