### ISSUE TITLE
AJA HDMI defaults to RGB

### ISSUE THREAD

**Issue by erichorwitz** [CESNET/UltraGrid#54]
In my brief testing it appears that the HDMI output is defaulting to RGB and I cannot change in from the uv command line. I have attempted to use the following command uv -d aja:YUV -r embedded IP

Can this only be changed in cables?

**Comment by MartinPulec** [comment]
Hi @erichorwitz, good question. I've checked the code and it indeed outputs for HDMI to RGB. IIRC, the problem was that I was not able to reasonably get the YCbCr out of HDMI. If you are able to do it reasonably in cables app, could you provide me a screenshot (ideally before and after) or describe changes you made? Ideally after starting UltraGrid with an option `:clear-routing`. I should be able to add the settings to UltraGrid then.

Just to your command, there can be also `:connection=HDMI` anyways - UltraGrid route SDI by default. Without that the result is quite undefined (UG doesn't implicitly clear routing so it may work but it depends on state of the router).

Regards,
Martin

**Comment by erichorwitz** [comment]
Martin

It appears that the default cable config for HDMI is to go through the CSC1 node before connecting to the HDMI port. Connecting directly to the HDMI port from the Framebuffer1 node provides correct looking image,

![AJA_HDMI_RGB](https://user-images.githubusercontent.com/38221640/79463061-5ab0a680-7fc6-11ea-820d-14ed527aaeb8.PNG)

![AJA_HDMI_YUV](https://user-images.githubusercontent.com/38221640/79463082-600df100-7fc6-11ea-849d-395b6dff1fa9.PNG)

**Comment by erichorwitz** [comment]
Also the Frame Store is set to YUV-8 and cannot be changed even if I change the aja setting between RGB and YUV.

**Comment by erichorwitz** [comment]
Some other interesting notes:

I rebuilt my Ubuntu systems and then recompiled everything again and was able to test a couple similar codecs. Libx265 and hevc_nvenc seem to cause the Aja to cable itself differently. It turns out that with the nvidia quadro p400 that I am using, RGB hevc_nvenc is not supported and thus the decoder always defaults to UYVY. The Aja configures itself to cable from the frame buffer to the CSC node to the HDMI. The issue is the frame buffer is set to YUV8 because of the decoder and doesn’t require the CSC node to be in-line.

If I use the libx265 encoder and decoder the signal on the Aja is routed from the frame buffer directly to the HDMI port even though the frame buffer is set to RGB. 

I am sending a 444 signal to the encoder input in both cases.

It’s almost like the software is doing the opposite of what it’s supposed to do. 

I haven’t dug into the code enough but would is be possible to provide options for the Aja to explicitly set the routing and output encoding? In cables I am unable to change hdmi settings, e.g. stmpe or full, RGB or yuv, etc. not sure if this is something that’s being controlled by the SDK or not.

Please let me know if you have any questions.

**Comment by MartinPulec** [comment]
Hi Eric,

thanks for information, I'll just briefly respond to some of your observations:

> It appears that the default cable config for HDMI is to go through the CSC1 node before connecting to the HDMI port. Connecting directly to the HDMI port from the Framebuffer1 node provides correct looking image,

This is because CSC converts YUV->RGB. I was not, however able to get the output directly out, anyways.

> Also the Frame Store is set to YUV-8 and cannot be changed even if I change the aja setting between RGB and YUV.

I think it is correct behavior – it corresponds with the received color spec, so if YUV is received, the eventual conversion is done on the board.

**Comment by MartinPulec** [comment]
> Some other interesting notes:
> 
> I rebuilt my Ubuntu systems and then recompiled everything again and was able to test a couple similar codecs. Libx265 and hevc_nvenc seem to cause the Aja to cable itself differently. It turns out that with the nvidia quadro p400 that I am using, RGB hevc_nvenc is not supported and thus the decoder always defaults to UYVY. The Aja configures itself to cable from the frame buffer to the CSC node to the HDMI. The issue is the frame buffer is set to YUV8 because of the decoder and doesn’t require the CSC node to be in-line.

I am not sure if I understood the last sentence. However, the routing is always done in UltraGrid explicitly.

> 
> If I use the libx265 encoder and decoder the signal on the Aja is routed from the frame buffer directly to the HDMI port even though the frame buffer is set to RGB.

I wouldn't say "even though" but rather just because. The HDMI output is always set to RGB, thus no color space conversion is performed.

> 
> I am sending a 444 signal to the encoder input in both cases.
> 
> It’s almost like the software is doing the opposite of what it’s supposed to do.

Well, it depends what you mean - the encoder encodes to the codec that is nearest to the input if possible. And output over HDMI is always set to RGB just because when I was testing it was the only viable solution. But if you say that YCbCr is displayed correctly maybe it is time to change the default behavior.

> 
> I haven’t dug into the code enough but would is be possible to provide options for the Aja to explicitly set the routing and output encoding?In cables I am unable to change hdmi settings, e.g. stmpe or full,

The option for the range may be should possible to add. I am just surprised that it is impossible to change in the cables.

>  RGB or yuv, etc. not sure if this is something that’s being controlled by the SDK or not.

As indicated above - this is possible for SDI. For HDMI it was disabled just because output YCbCr hadn't worked.

**Comment by MartinPulec** [comment]
@erichorwitz, which display do you use? I've tried with BMD Video assist and a Decklink capture card and for both both YUV and RGB worked fine (transcoded all to RGB). Connecting YUV framebuffer directly to HDMI output looked to work, on the other hand connecting RGB framebuffer through CSC didn't look to work at all.

**Comment by erichorwitz** [comment]
I was using a Dell computer monitor and a Samsung TV. I was able to get a BMD 4k monitor to output video and audio correctly via hdmi to an Onkyo receiver.

With the AJA output I was able to get video to work correctly through the CSC node with the frame buffer outputting RGB. If I am not mistaken the HDMI port in cables is set to YUV all the time which might be the problem. I think UG, when it detects an RGB decode, connects the frame buffer directly to the hdmi port. The hdmi port appears to be hard set to YUV and you cannot change the its settings in cables, therefore it doesn’t decode correctly. Unfortunately I removed the AJA card from the receiver so I will have to swap the cards again to test.

**Comment by MartinPulec** [comment]
Thanks for info @erichorwitz. I'll therefore try to add a possibility to force the mode with ':YUV' option. As I said, I had no success converting the RGB framebuffer to YUV in Cables, but maybe it helps to set the hdmi output format explicitly to YCbCr. It is not sure, however - the Cables application issues exactly the same commands as UltraGrid would, so the only difference may be that UltraGrid may set it before the stream is started (maybe if AJA can't change it while the stream is running?).

Also it may be useful to add a option for UltraGrid not to route the signal at all for debug and specific use cases (to let the user to wire/set the device manually and UltraGrid leaves it intact).

**Comment by erichorwitz** [comment]
I did some more testing today and think I might have figured out what is going on... I think when UG sets up the Aja it wants to send RGB out the hdmi however the hdmi port is set to YUV by default. If you manually change the hdmi port to RGB I was able to get picture and audio. Unfortunately my TV doesn’t support RGB so it’s green but I am getting picture and audio.

Cable routing after cable-reset

Setup 1: frame buffer decoding YUV
Framebuffer(yuv)->CSC(yuv to rgb)->HDMI(yuv)


Setup 2: frame buffer decoding RGB
Framebuffer(RGB)->HDMI(yuv)

I was able to get the RGB to YUV csc node to work if the framebuffer is decoding RGB. Maybe is was related to the firmware? I was running an old 2014 firmware and upgraded to the latest 2018.

That being said it would be super helpful to have a :YUV setting that sets the whole pipeline up as YUV, and if it detects an RGB framebuffer then it would use the CSC node to convert to YUV. Basically the opposite of the default.

**Comment by MartinPulec** [comment]
I've just pushed a version that honors YUV option for HDMI. It seems to work for me, IIRC it didn't before. If so, I'd perhaps make a default option to keep the color space to the output while keeping the options to force either RGB or YCbCr output.

I've added also `:no-setup` and `:no-setup-route` (first opt is superset of the second) for debugging purposes - you should be able to config/route via Cables prior to running UltraGrid which then doesn't override the setting.

**Comment by putyoutoosleep00** [comment]
Loser

**Comment by MartinPulec** [comment]
@erichorwitz I don't recall much details about this issue but reading back my comments it could be resolved if I am not mistaken? Or we can dismiss it if you are no longer intersted in it (it has been more than 2 years 'till now).
