### ISSUE TITLE
unable to transcode audio with reflector

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#56]
Getting the video to transcode on a reflector was easy.  But I have been unable to get the reflector to transcode audio.  I've tried several different syntaxes.  All come out the same.

```
hd-rum-transcode 80M 6006 -P 5006 --audio-codec AAC:bitrate=128K XXX.XXX.XXX.XXX
UltraGrid 1.5+ (tags/continuous rev 2d93c615 built Apr 12 2020 17:33:28)

Error: invalid option '--audio-codec'
```

**Comment by MartinPulec** [comment]
HI Alan, that's correct. The transcoding of the audio is currently not supported.

**Comment by alatteri** [comment]
thank you for the clarification
