### ISSUE TITLE
hd-rum-transcode unable to have multi recievers when doing transcode

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#57]
If using reflector in transcode mode, on same machine as sender, only one IP will get sent the transcode segment

For instance if I want recipient A&B to receive an H264 stream and C to get a JPEG stream, you would have to instigate separate transcode segments for each A & B instead of A&B getting reflected the same encode stream.

Example:

`hd-rum-transcode 8M 7000 -P 5004 -c libavcodec:codec=H264 A.A.A.A B.B.B.B -P -c libavcodec:codec=JPEG C.C.C.C`
This won't work.  Only A.A.A.A will get the H.264 stream.  Nothing gets sent to B.  C does get the JPEG stream.

To make this work for A & B, you would have to do:
`hd-rum-transcode 8M 7000 -P 5004 -c libavcodec:codec=H264 A.A.A.A -P 5004 -c libavcodec:codec=H264 B.B.B.B -P 5004 -c libavcodec:codec=JPEG C.C.C.C`

This is very in-efficient as now you are having to do double H.264 to be able to send to A & B.  This could result in excessive CPU load that might not be able to accommodate, especially when really you are encoding the same thing twice.

**Comment by MartinPulec** [comment]
This is mostly correct. Except that the information:

>  Nothing gets sent to B.

This shouldn't be entirely correct. When no compression is set for a host, the input stream is forwarded intact, not discarded. If so, it is a bug.

But generally I agree that it is would be useful to reflect one transcoded stream to more than receivers. Until that, combining a transcoding+retransmitting reflector could be a viable alternative (although not much elegant).

**Comment by mpiatka** [comment]
This was changed a while ago (in february I think). Now doing 
```
hd-rum-transcode 8M 7000 -P 5004 -c libavcodec:codec=H.264 A.A.A.A -P 5004 -c libavcodec:codec=H.264 B.B.B.B
```
will reuse compressed video stream for all recipients with the same compression setting string.
