### ISSUE TITLE
How to start stream from url via web interface

### ISSUE THREAD

**Issue by rickerd** [CESNET/UltraGrid#6]
Hi,

I'm trying to restream via rtmp to YouTube or another stream service.
My ipcamera has rtsp but i need a service that restreams this to a service.

I can start the stream via nginx but i want to setup everything dynamically so I can start multiple sources to different streaming services.

I hope you understand me and can help me.

I dont want to show the stream via a personal website. I only want to stream to YouTube so i can embed it into my website.

**Comment by MartinPulec** [comment]
I think that easiest way would be to restream it with VLC rather than with UltraGrid.

Regards,
Martin
