### ISSUE TITLE
HDMI HDR Metadata tags with Decklink

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#60]
Hello,

Is there a way to enable HDR metadata tags when outputting via Decklink HDMI?

Thanks,
Alan

**Comment by MartinPulec** [comment]
Hi Alan, currently no, but it will be possible to add. However, may I ask which metadata, or rather where the metadata should come from? Given statically from command-line to playback? Or captured (by DeckLink) and passed to playback?

Thanks,
Martin

**Comment by erichorwitz** [comment]
I don’t know what Alan would want but I would definitely want a static command line to force the output to HDR. That way no matter what the source it can be flagged as HDR. It would also be helpful to have the HDR flags be able to do both do both st2084-P3 as well as st2084-rec2020. I know on an LG C9 you can toggle between the two color spaces in HDR which use a different LUT in the TV.

Can the blackmagic cards tunnel Dolby Vision metadata. If so, in the long run, that would be super helpful to be able to maintain and send over Ultragrid. 

Sorry to jump in the middle...

**Comment by MartinPulec** [comment]
@alatteri @erichorwitz I can provide a option for dynamic range defined in section of 3.68 (pg. 245)
defined in the [SDK](https://github.com/CESNET/UltraGrid/files/4614222/Blackmagic.DeckLink.SDK.pdf), eventually also color space (3.66) for as a starting point. Do you see anything else interesting?

**Comment by MartinPulec** [comment]
Okay, I've looked at it and it is somehow more complex. I've checked 
[SignalGenHDR sample](https://github.com/CESNET/UltraGrid/files/4615017/SignalGenHDR.zip) from the SDK. It is needed to fill the whole metdata struct (sec 3.62 in the manual).

There is, however default colorimetric primitves in above-mentioned sample - it is default Rec 2020 `{ 0.708, 0.292, 0.170, 0.797, 0.131, 0.046, 0.3127, 0.3290 }` (X,Y pairs of R,G,B,white), min/max luminance 0.0001/1000 (cd/m² ?), max frame content level 1000, average 50 cd/m² and transfer functions SDR/HDR/PQ/HLG.

Please correct me if I misunderstood something.

So I could provide parameter for the transport function... Is there need to set/supply by user something else? It would be possible to let user specify all values but not much user friendly. And I am not sure if it makes much sense to use different color primitives, maybe only luminance levels? On the other hand, the SDK sample sliders for all values.

**Comment by alatteri** [comment]
Hi Martin,

Looking at the SDK, BMDDynamicRange, BMDColorspace & bmdDeckLinkFrameMetadataColorspace definitely might be the start of what need.  I'm not clear if all the bmdDeckLinkFrameMetadataHDR* variables would also need to be set.

The use case, is the *most* TVs only engage a specific HDR mode if it resides in the input HDMI metadata.  LG TV for instance.  On Sony OLED TVs, you can manually force a specific HDR mode, such as HLG, HDR10, etc.  

So in the case of UG, and output via BMD Decklink HDMI, with an input stream captured from SDI.  With a Sony TV, we can set mode to HDR10, and it works great, but LG just sees it as a normal signal, no HDR.  So if there was a way to tag the Decklink HDMI output, would be great.

**Comment by MartinPulec** [comment]
I've currently pushed a commit 730d6346 that allows the use an option in format `:HDR[=HDR|PQ|HLG|<int>]` (the optional part specifies EOTF, int is the transfer function index specified by CEA 861.3). Otherwise all values are pre-set to the values I've mentioned above. If needed, it will be possible to pass also other values as an parameter.

**Comment by alatteri** [comment]
Awesome... going to test this today.  Do I add the -HDR flag on capture or playback device?

**Comment by MartinPulec** [comment]
It is on playback.

**Comment by erichorwitz** [comment]
Thank you so much Martin!

**Comment by alatteri** [comment]
```
 uv -d decklink:HDR=HDR
UltraGrid 1.6+ (tags/continuous rev 80651114 built Jul 31 2020 18:02:49)

Display device   : decklink
[Decklink display] Warning: unknown options in config string.
Unable to open display device: decklink
Exit

```

```
 uv -d decklink:HDR=PQ
UltraGrid 1.6+ (tags/continuous rev 80651114 built Jul 31 2020 18:02:49)

Display device   : decklink
[Decklink display] Warning: unknown options in config string.
Unable to open display device: decklink
Exit

```

**Comment by alatteri** [comment]
Hi guys.... Is my syntax for using HDR incorrect? I have also tried `uv -d decklink:HDR` and it produced the same error.

**Comment by MartinPulec** [comment]
Hi, oh, my bad, I've just tested "HDR" without specifying EOTF and there was a small mistake in parsing the other options. Should be fixed now.

**Comment by alatteri** [comment]
Hi Martin,

I've tried both `-d decklink:HDR=HDR` and `-d decklink:HDR` with `ba44dc5a`.  Results in just black output.  Using only `-d decklink` give a normal **NON-HDR** output.

**Comment by MartinPulec** [comment]
Hi Alan,
I am not sure if UltraStudio HD Mini supports HDR. I've tested and unsupported device outputs blank if set to HDR. Can you please try current code (commit at least 987ab568)? I've added there a check if HDR is supported, if not, UltraGrid exits.

**Comment by alatteri** [comment]
Hi Martin.

I will give it a try.  And I was thinking also it may be a hardware limitation of the HD Mini.  I will have access to a 4K Mini tomorrow to test with.  

Thanks again.

**Comment by MartinPulec** [comment]
No problem, I'll be glad if you will be able to test since it is currently written mostly blindly. Actually no device I've tested reports that it supports HDR - DeckLink 4K Extreme displays blank picture, DeckLink 8K Pro displayed the video actually, API was requesting the HDR metadata but the card doesn't report to support HDR, either. Which seems plausible if the metadata are transferred over HDMI only because the card is SDI-only.

**Comment by alatteri** [comment]
Hi Martin,

Latest build on UltraStudio 4K Mini reports no HDR support.  But that is weird since it is listed in their specs.

```
uv -d decklink:HDR
UltraGrid 1.6+ (master rev 987ab568 built Aug  5 2020 08:34:16)

Display device   : decklink
Capture device   : none
Audio capture    : none
Audio playback   : none
MTU              : 1500 B
Video compression: none
Audio codec      : PCM
Network protocol : UltraGrid RTP
Audio FEC        : none
Video FEC        : none

Created new RTP session with SSRC 0x2b03c69d.
[Decklink display] Using low-latency mode. In case of problems, you can try '-d decklink:no-low-latency'.
[Decklink display] Using device UltraStudio 4K Mini
[Decklink display] HDR requested, but card doesn't support that.
Unable to open display device: decklink
Exit
```
![Screen Shot 2020-08-05 at 9 40 20 AM](https://user-images.githubusercontent.com/625982/89439971-d498a700-d6ff-11ea-807c-d7d27308b8e9.png)

**Comment by MartinPulec** [comment]
Oh, ok, bad check, can you try it now? :-)

**Comment by alatteri** [comment]
Hi Martin,

Sorry it took a bit to test this.  A mix of works and doesn't.

1.
```
 uv -d decklink:HDR=PQ
UltraGrid 1.6+ (master rev 300345af built Aug 13 2020 15:21:28)
[Decklink display] Wrong HDR mode "PQ": stoi
Unable to open display device: decklink
Exit
```
2. But this` uv -d decklink:HDR=2` successfully successfully triggers TV HDR mode.
3. both `HDR=HLG` and `HDR=3` successfully triggers TV HDR mode.
4. Even though the TV goes into HDR mode, it is not getting triggered to switch to bt2020 color space.  Don't know if that is something that is in Decklink API that can be added to UG.
5. `HDR=HDR` or `HDR=1` does nothing.  TV doesn't switch.
6. going back to SDR/normal decklink mode, does not instigate the TV to exit HDR.  I have to pull the HDMI on the decklink and re-insert.  Example.  in `decklink:HDR=2` mode.  Then switch to just `decklink`, TV is still in HDR mode.  Don't know if there is some type of reset on the Decklink that can be called.

Recap
`HDR` , `HDR=HDR` ,  `HDR=1` does nothing
`HLG/2/3` successfully trigger TV switch to HDR mode, but **NOT** 2020 colorspace/gamut
TV doesn't not switch out of HDR, even when only `decklink` is called, unless HDMI cable is reset

**Comment by MartinPulec** [comment]
1. ok thanks, that was a typo in code - fixed
4. I see - well, if you look into the UG code, this should be values defined by `kDefaultRec2020Colorimetrics` so I guess that it should be set in metadata. Maybe you can try to set different values if it does a difference?
6. assuming that you have tried `-d decklink:HDR=SDR` (or 0) as well?

You can also try the _SignalGenHDR_ sample in the SDK.

If you tell me what values to set (or make available through cmdline), I can do that.

I am afraid that I am not sure how to test - we have a Shogun Inferno that should be able to display HDR. But even if I had some material to test with, I don't know how to "see" if it is correct or not. Maybe some picture with Rec. 2020 that has colors that cannot be represented by 709 (assuming that the monitor is really able to display it)?

**Comment by MartinPulec** [comment]
I've added a check if device supports color space metadata (it is reported by the API). If not, it just prints a warning (doesn't exit) - can you check it out?

Thanks, Martin

**Comment by alatteri** [comment]
> 3\. assuming that you have tried `-d decklink:HDR=SDR` (or 0) as well?


Hi Martin... Yes, tried that too.

**Comment by alatteri** [comment]
> 2\. I see - well, if you look into the UG code, this should be values defined by `kDefaultRec2020Colorimetrics` so I guess that it should be set in metadata. Maybe you can try to set different values if it does a difference?

Those values all look good except for kDefaultMaxFALL.  All our AJA SDI->HDMI converters have 400 as default.  Would there be a way to add a value to override these default parameters in UG?

**Comment by alatteri** [comment]
> > 3. assuming that you have tried `-d decklink:HDR=SDR` (or 0) as well?
> 
> Hi Martin... Yes, tried that too.

Reboot of the UG receiver computer kicks TV back in SDR mode.  It is an acceptable solution.

**Comment by MartinPulec** [comment]
> > 2. I see - well, if you look into the UG code, this should be values defined by `kDefaultRec2020Colorimetrics` so I guess that it should be set in metadata. Maybe you can try to set different values if it does a difference?
> 
> Those values all look good except for kDefaultMaxFALL. All our AJA SDI->HDMI converters have 400 as default. Would there be a way to add a value to override these default parameters in UG?

I've added `<key>=<value>` setting of some of those values, see `-d decklink:hdr=help`, eg. in your case, I guess something like:

    uv -d decklink:HDR=PQ,maxFALL=400

EOTF specification is mandatory if specifying some optional values.

**Comment by MartinPulec** [comment]
> Reboot of the UG receiver computer kicks TV back in SDR mode. It is an acceptable solution.

Ok, good to know. I don't think there is something that can be done about in UltraGrid - you can either set the metadata to some defined value (one would expect SDR in this context) or don't set it. I didn't notice any other option in the SDK.

**Comment by MartinPulec** [comment]
> I've added `<key>=<value>` setting of some of those values

... but not pushed it to the GIT, in case that you checked it yesterday. Now it should be there.

**Comment by alatteri** [comment]
Hi Martin.... This latest commit is working great.  Fixes all the issues except switching back to SDR, but the reboot method is fine for that.  Thanks a bunch.  Closing this issue.
