### ISSUE TITLE
Support for Blackmagic UltraStudio hardware encoder

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#63]
Hello,

The Blackmagic UltraStudio line has built in hardware h.265 encoder.  It would be great to be able to utilize this for encoding.

Thanks,
Alan

**Comment by MartinPulec** [comment]
I agree, do you know which ones support that? I've found only UltraStudio 4K Extreme 3. This would be a bit tricky, since I don't have any "hands-on" and there is no relevant sample in SDK. But theoretically I can try it blindly then.

**Comment by alatteri** [comment]
Hi Martin... You are right, only the 4K Extreme 3 seems to support this.  
We don't have any of those boxes, just the Mini HD and 4K Mini.  So I'm going to close this for now.  Thanks again for your interest.
