### ISSUE TITLE
List available pixel_fmt for decoders

### ISSUE THREAD

**Issue by erichorwitz** [CESNET/UltraGrid#66]
Is there a way to list available pixel_fmts for decoders? For the encoder if it’s typed incorrectly the application will print a list of available formats but not if you do the same for the decoders.

**Comment by MartinPulec** [comment]
Hi Eric,

you mean for the `decoder-use-codec` parameter? Well, it needs to be one that a display supports. In theory it should be listed by something like `-d decklink:help`. It is currently not there but I'll add (but it is the same set as for decklink on capture `-t decklink:help`.

Martin

**Comment by erichorwitz** [comment]
Right however if you input something that is not supported you have no idea why. Also it doesn't seem to support all the same encoder formats as are supported on the decoder.

Does decoder-use-codec affect the libavcodec or only the decklink? Also the output of the decklink does not have the codec= option like the recorder.

**Comment by MartinPulec** [comment]
Hi Eric,
well, yes, I can see the problem. I've pushed something different in the end. If the reconfiguration fails, it just prints the codecs that display reports as supported. 

To your question - well, it affects both. The DeckLink is obvious but it then influences also the libavcodec to see to which format to decode. The codec option is not needed, it is handled usually automatically (and thus keeping the codec if possible). And this also doesn't make sense in some case - let say you'd capture and tell decklink to display RGBA - it isn't capable to handle that. Approximately a substitution is the `decoder-use-codec` option. It can be used if the deduction is not optimal (eg. decoder attempts to keep color space but user wants a bit dept).

**Comment by MartinPulec** [comment]
`--param decoder-use-codec=help` should be working now as well.
