### ISSUE TITLE
Update to latest Decklink SDK

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#67]
Hi,

Feature Request.  It's been about a year since SDK11.0 was release, and current version is 11.5.X.  Wondering if it is beneficial to update to the latest version?

Thanks,
Alan

**Comment by MartinPulec** [comment]
Hi, well, as far as I know the question has two answers:

- using a higher SDK version has the advantage that it supports features that the lesser version doesn't. So if using some of these features, it is required to update
- using higher version requires presence of drivers at least the same as the SDK version

So, in my opinion, provided that we do not add any new feature that would require newer version, there is no advantage of doing that - on the contrary it would force users to update their drivers.

**Comment by alatteri** [comment]
Hi Martin.

I understand the logic here.  Since BMD drivers are free, and easy to install, maybe there could be some type of yearly update to the latest SDK.  Although, yeah, not much has changed in the SDK since 11.0.

Thanks for the consideration.
Alan
