### ISSUE TITLE
udp-queue-len clarification?

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#68]
Hello,

In some of the newer commits, I see there is an option to specify "udp-queue-len".  Looking at the code, seems it is calculating a default value based off MTU of 1280 and a 1920x1080 frame resolution.  Is there any benefit in manually specify a different "udp-queue-len" for higher resolution frames?  What are the ramifications of having different/larger udp-queue-len??  Would it add more latency or reduce stream stability?

Thanks,
Alan

**Comment by MartinPulec** [comment]
Well the option is there for a long time ago. Unless you send either uncompressed frames, or the receiver doesn't catch up it won't have any effect. If you don't experience problems, I wouldn't touch that. There might be better heuristics but I don't think it is needed - I don't remember I needed to set a different value (except of very high-bitrate streams, let say 10+ Gbps). But if you would able to improve some characteristic by tweaking this parameter let me know, the value can be adjusted. But as I said, in my opinion there is no reason to change the value under usual circumastances.

Martin

**Comment by alatteri** [comment]
Thank you for the clarification.  I won't touch it.
