### ISSUE TITLE
Unable to set Intra Refresh: Option not found

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#70]
When using x265 as the encoder, this error is displayed on the encoder.  I'm confused by this since the x265 docs clearly have this as a feature.
https://x265.readthedocs.io/en/default/cli.html#cmdoption-intra-refresh

Also further down in the info display there are mentions of Intra Refresh being enabled.

[lavc] **Unable to set Intra Refresh: Option not found**
[lavc] Warning: Codec doesn't support slice-based multithreading.
[lavc] Setting preset to ultrafast.
x265 [info]: HEVC encoder version 3.2.1+1-b5c86a64bbbe
x265 [info]: build info [Linux][GCC 9.3.0][64 bit] 12bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [warning]: halving the quality when psy-rd is enabled for 444 input. Setting cbQpOffset = 6 and crQpOffset = 6
x265 [warning]: **Open Gop disabled, Intra Refresh is not compatible with openGop**
x265 [warning]: **Scenecut is disabled when Intra Refresh is enabled**
x265 [warning]: Keyint value is very low.It leads to frequent intra refreshes, can be almost every frame.Prefered use case would be high keyint value or an API call to refresh when necessary

**Comment by MartinPulec** [comment]
Thanks for reporting. There was actually a problem but it didn't actually influence libx265 but libx264 instead. The option was not set for libx264 at all but was mistakenly set for libx265 resulting in libx264 not using the intra-frame refresh (but libx265 does, the message was just a side effect). I've just fixed that.

**Comment by alatteri** [comment]
Confirmed fixed.  Thanks,
