### ISSUE TITLE
Raspberry Pi: h264_omx encoder generates invalid stream

### ISSUE THREAD

**Issue by R6A8kJOk** [CESNET/UltraGrid#72]
Hi,

trying to stream from an official Raspberry High Quality Camera on a Raspberry Pi 3B to itself, using

```
./uv -t v4l2:codec=YU12:size=1280x720:fps=30:RGB -c libavcodec:codec=H.264:encoder=h264_omx -P 8000 127.0.0.1
UltraGrid 1.6 (built Jul 14 2020 19:28:25)

Display device   : none
Capture device   : v4l2
Audio capture    : none
Audio playback   : none
MTU              : 1500 B
Video compression: libavcodec:codec=H.264:encoder=h264_omx
Audio codec      : PCM
Network protocol : UltraGrid RTP
Audio FEC        : none
Video FEC        : none

Created new RTP session with SSRC 0x746977ff.
Display initialized-none
vidcap_v4l2_init
Enable video input: 1280x720 30.000000 fps progressive, codec RGB
Video capture initialized-v4l2
Created new RTP session with SSRC 0x1aefd016.
[lavc] Using codec: H.264, encoder: h264_omx
[lavc] Setting bitrate to 7741440 bps.
[lavc] Warning: Unknown encoder h264_omx. Using default configuration values.
[lavc] Warning: Codec doesn't support slice-based multithreading.
[lavc] Warning: Unable to find suitable preset for encoder h264_omx.
[h264_omx @ 0x1fcc4c0] Using OMX.broadcom.video_encode
[lavc] Selected pixfmt: yuv420p
[V4L2 capture] 70 frames in 5.02684 seconds = 13.9253 FPS
[V4L2 capture] 77 frames in 5.00555 seconds = 15.3829 FPS
```

Receiving like this results in no picture, and these warnings:
```
./uv  --param force-lavd-decoder=h264_mmal  -d gl -P 8000
UltraGrid 1.6 (built Jul 14 2020 19:28:25)

Display device   : gl
Capture device   : none
Audio capture    : none
Audio playback   : none
MTU              : 1500 B
Video compression: none
Audio codec      : PCM
Network protocol : UltraGrid RTP
Audio FEC        : none
Video FEC        : none

Created new RTP session with SSRC 0x41209cf0.
GL setup: fullscreen: OFF, deinterlace: OFF
Display initialized-gl
Video capture initialized-none
Created new RTP session with SSRC 0x4da4d4d5.
[video dec.] New incoming video format detected: 1280x720 @30.00p, codec H.264
[lavd] Unable to open decoder h264_mmal.
[lavd] Using decoder: h264
[h264 @ 0x721037c0] non-existing PPS 0 referenced
[h264 @ 0x721037c0] decode_slice_header error
[h264 @ 0x721037c0] no frame!
[lavd]  Error while decoding frame (rc == -1094995529): Invalid data found when processing input.
[video dec.] Detected internal codec: UYVY
[h264 @ 0x721037c0] non-existing PPS 0 referenced
[h264 @ 0x721037c0] decode_slice_header error
[h264 @ 0x721037c0] no frame!
[lavd]  Error while decoding frame (rc == -1094995529): Invalid data found when processing input.
[video dec.] Detected internal codec: UYVY
[video dec.] Successfully reconfigured display to 1280x720 @30.00p, codec UYVY
libGL error: MESA-LOADER: failed to retrieve device information
[lavd] Using decoder: h264_mmal
[video dec.] Successfully reconfigured display to 1280x720 @30.00p, codec UYVY
[lavd] Using decoder: h264_mmal
[lavd]  Error while decoding frame (rc == -11): Resource temporarily unavailable.
[...]
[lavd]  Error while decoding frame (rc == -11): Resource temporarily unavailable.
[h264_mmal @ 0x72003910] Did not get output frame from MMAL.
[lavd] Unexpected return value -1313558101
[h264_mmal @ 0x72003910] Did not get output frame from MMAL.
[lavd] Unexpected return value -1313558101
Video dec stats (cumulative): 1 total / 0 disp / 0 drop / 0 corr / 1 missing.
Pbuf: total 896/896 packets received (100.00000%).
Exit
```

Transmitting H264 from a Mac to this Raspberry works (although too slow for 720p30), transmitting from the Raspberry to the Mac fails in a similar fashion.
```
[lavd]  Error while decoding frame (rc == -1094995529): Invalid data found when processing input.
[h264 @ 0x7fb2c4839000] non-existing PPS 0 referenced
[h264 @ 0x7fb2c4839000] decode_slice_header error
[h264 @ 0x7fb2c4839000] no frame!

```
Transmitting some other codec, like MJPEG from the Raspberry also works.

I believe the OMX encoder is not configured correctly, maybe related to this patch (that I'm not using right now)?
https://github.com/Serveurperso/FFmpeg/commit/6e410823e63103342e8fc3407ff6698808d4d1ef

Anything you can do about this?

Bonus question, how do i correctly format the `lavc_opts` parameter to set options on the encoder? Trying to set the profile on the OMX encoder to no avail.

Thank you!

**Comment by MartinPulec** [comment]
Hi @R6A8kJOk,

you are most probably correct, that the linked patch could help. AFAIK, by default, the stream is without SPS/PPS repeated so if you don't catch the first frame (which you most likely won't with UltraGrid because it drops few first frames). If you compile by yourself it could be doable - I'll try to figure it out also for official AppImages (it may need to be prebuilt).

> Bonus question, how do i correctly format the lavc_opts parameter to set options on the encoder? Trying to set the profile on the OMX encoder to no avail.

The correct format should be simply `-c libavcodec:encoder=h264_omx:preset=baseline`. UltraGrid passes unrecognized options to the codec directly.

Regards,
Martin

**Comment by R6A8kJOk** [comment]
Thank you, I will give that a try. AppImage gave a glibc error when I tried it on Raspbian.

**Comment by MartinPulec** [comment]
> AppImage gave a glibc error when I tried it on Raspbian.

Well, yeah, sorry for that. I suppose that this is on Raspberry Pi OS < 2019-06-20? The thing is that the current AppImage is built on Debian Buster-based Raspberry OS which has higher glibc requirements. In theory it could be possible to build on older Stretch-based one but this would require the toolchain (incl compiler, since there are not backports) old. That's why we probably won't to.

Martin

**Comment by MartinPulec** [comment]
Another status update - I can confirm that the proposed change helps, it is already included in the ARMhf continuous build (although you won't be perhaps able to use it as you've written above).

**Comment by R6A8kJOk** [comment]
OK great, thanks. Will try with newer OS. I just used what I had on that SD card.

**Comment by MartinPulec** [comment]
Closing for longer inactivity - supposing that the issue is fixed.
