### ISSUE TITLE
[DeckLink capture] Dropping audio packet, queue full.

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#73]
I just did an OS rebuild of Ubuntu 20 with BMD Decklink 11.5.1, and fresh compile of UG.  I'm getting these random warnings in the UV output, which results in stuttered video frames.

SDI 2K R12L 8 channel embedded audio

  Any thoughts?
```
UltraGrid 1.6+ (tags/continuous rev 9a81e9af built Jul 27 2020 19:17:15)

[DeckLink capture] Dropping audio packet, queue full.
[DeckLink capture] Dropping audio packet, queue full.
[DeckLink capture] Dropping audio packet, queue full.
[DeckLink] Audio frame too small!
[DeckLink] Audio frame too small!
[DeckLink] Audio frame too small!
[DeckLink] Audio frame too small!
```

**Comment by alatteri** [comment]
Probably related to this commit. c949fa3d06e49f45fa639bf9facb544aa7d7a54d

**Comment by MartinPulec** [comment]
Hi Alan,

well the commit shouldn't actually break anything, I think that it is rather a symptom of other problem, maybe a performance? Can you check if the compression is able to compress the nominal frame rate?

Also, is this occurring at the beginning only or all the time? If the first case, I can imagine that the initialization of video compression takes some time while the limited audio queue is not able to hold the frames. This should not be bad, on contrary having the unlimited queue is quite dangerous. Also, it may be possible to capture audio only if there is currently no video (or the video pipeline stalls) - I'll eventually add it.

Martin

**Comment by alatteri** [comment]
Hi Martin,

This is on a brand new AMD Ryzen 3950X server which should be much faster than my old machine, which was based on Intel E5-2690v3.

This is happening random throughout the stream.   Would increasing the audio queue to a larger value help?

**Comment by alatteri** [comment]
as a quick test, I changed
`constexpr const size_t MAX_AUDIO_PACKETS = 10;`
to use a value of `20`

In my cursory testing, the issue is now NOT happening.

**Comment by MartinPulec** [comment]
Ok, no problem - as a quick you can use it (or I'll push it then). The actual value doesn't matter much, the point is not to run indefinitely.

**Comment by alatteri** [comment]
Hi Martin,

I'm pretty embarrassed today.  Not only was my bug report about 10/12bit completely my fault, but I think this one too.  In setting up the new 1U server I mentioned, I forgot to install the fan shroud cover.  So the CPU/PCI card was not getting optimal airflow, and I think you're right, it was throttling down and intermittently not encoding nominal frame rate (maybe co-inciding with Dropping audio packet) .

So in my current testing, with fan shroud installed, `25eef88c` (even without the `packets = 20` change) seems to be doing just fine, 10/12bit RGB 444 with audio.  My apologies for wasting your time.

**Comment by MartinPulec** [comment]
Hi Alan, don't worry, actually there is a point - I am actually thinking that it may be worth sending the audio even if the video pipeline is slow. Although it is not desired, it may happen as you have seen. And if so, it may be better to keep at least the audio.

**Comment by alatteri** [comment]
Hi Martin,

I agree.  Having the audio keep going makes any video glitches seem "less bad".  When there are video hits, and the audio is skipping too, that is hard on the brain.
