### ISSUE TITLE
NDI support compile regression from 1.6 --enable-ndi fails (ubuntu 18)

### ISSUE THREAD

**Issue by stranger2904** [CESNET/UltraGrid#75]
Hello
I was banging my head for a while trying to enable ndi support using the latest GIT version.
It was failing like this:
`checking Processing.NDI.Lib.h usability... yes
checking Processing.NDI.Lib.h presence... yes
checking for Processing.NDI.Lib.h... yes
checking for NDIlib_initialize in -lndi... yes
./configure: line 16270: test: `)' expected
configure: error: NDI not found!`

even though libndi is available and detected by the system

But I once I used release version with the same command line parameters - all worked out right away.

Please let me know if any additional info/logs required

**Comment by MartinPulec** [comment]
Hi, thanks for reporting, there was just a missing space in the configure script that should have caused that. Fixed in [CESNET/UltraGrid](https://github.com/CESNET/UltraGrid). Can you please try it now?

Thanks,
Martin

**Comment by stranger2904** [comment]
All good, thank you for the quick fix !
