### ISSUE TITLE
Ultragrid display received FFmpeg stream

### ISSUE THREAD

**Issue by pcarrillom** [CESNET/UltraGrid#79]
Hello,

Is there a way to display with UltraGrid (uv -d) one FFmpeg generated stream? 

If so, which format, protocol, codec is recommended?

Thanks!

**Comment by MartinPulec** [comment]
Hi @pcarrillom,

assuming that you think a FFmpeg generated RTP stream? This is currently not possible because UltraGrid uses its own packet format. Although also backed by RTP, it is not RFC compliant for media payloads.

Martin

**Comment by MartinPulec** [comment]
I am closing the issue now because it was formulated as a question, not a feature request - if you wish, you can repost or recycle it as such.
