### ISSUE TITLE
AppImage does not run on Xubuntu 18.04, libs missing

### ISSUE THREAD

**Issue by probonopd** [CESNET/UltraGrid#81]
Thanks for making an AppImage. However, it does not run e.g., on Xubuntu 18.04:

```
This application failed to start because it could not find or load the Qt platform plugin "xcb".
```

It seems that this is caused by some libraries that are required but not bundled:

```
me@host:~$ LD_LIBRARY_PATH=squashfs-root/lib/ ldd squashfs-root/lib/qt5/plugins/platforms/libqxcb.so | grep not
	libxcb-render-util.so.0 => not found
	libxcb-image.so.0 => not found
	libxcb-icccm.so.4 => not found
	libxcb-randr.so.0 => not found
	libxcb-keysyms.so.1 => not found
	libxcb-xkb.so.1 => not found
	libxcb-xkb.so.1 => not found
```

Tools like `linuxdeployqt` can take care of such things automatically for you.

**Comment by MartinPulec** [comment]
Hi, 

>     This application failed to start because it could not find or load the Qt platform plugin "xcb".
>
> It seems that this is caused by some libraries that are required but not bundled:

Correct, it is manually removed, see [here](https://github.com/CESNET/UltraGrid/blob/a76979ab801921b2b34e0dcedcb338848f96e5d8/data/scripts/Linux-AppImage/create-appimage.sh#L49). I may remove it from the blacklist although I am not sure if it is safe.

> Tools like linuxdeployqt can take care of such things automatically for you.

Yes, we plan to do that, at least in order not to having to maintain own list of excludes. But when I lastly tried it, it didn't work for me out of the box - there was some trivial issue AFAIK, unfortunately I didn't have a time to solve it then. I'll take a look at it again later on.

**Comment by MartinPulec** [comment]
Currently, I use your [exclude list](https://raw.githubusercontent.com/probonopd/AppImages/master/excludelist) at least. The change is in commit 4f3576c1 and should already be reflected by current builds. This should the above libraries in the AppImage (since not listed in the list).

**Comment by probonopd** [comment]
Thank you very much @MartinPulec :+1:

**Comment by MartinPulec** [comment]
I thank you very much as well. And I'll use linuxdeployqt then, I just didn't have the time for it yet.
