### ISSUE TITLE
NVENC pixel format

### ISSUE THREAD

**Issue by alatteri** [CESNET/UltraGrid#82]
Hello,

When utilizing R10k or R12L on a decklink device, with `libavcodec:encoder=hevc_nvenc` it is defaulting to `bgr0`

`[hevc_nvenc @ 0x7f1f80001680] supports NVENC
[lavc] Codec supported pixel formats: yuv420p nv12 p010le yuv444p p016le yuv444p16le bgr0 rgb0 cuda
[lavc] Usable pixel formats: gbrp10le rgba gbrp bgr0 yuv422p10le
[1598236276.669] [lavc] Selected pixfmt: bgr0`

My understanding is that bgr0 is an 8 bit format.  Seems like yuv444p16le would be more accurate color space for the input.

Thanks.

**Comment by alatteri** [comment]
additional when using `libavcodec:encoder=hevc_nvenc --param lavc-use-codec=yuv444p16le --verbose`
I gives this warning.

```
[1598237551.861] [lavc] Selected pixfmt: yuv444p16le
[1598237551.862] [lavc] Failed to find a way to convert R10k to yuv444p16le
[1598237551.862] [lavc] Attempting to use swscale to convert.
[1598237551.862] [lavc] Using swscale to convert gbrp10le to yuv444p16le.
```

**Comment by MartinPulec** [comment]
It is only a matter of policy - currently the color space is kept. In future it would be perhaps best to let the user configure if it prefers rather bit depth than color space preservation (or subsampling).

I agree in general but I am not sure if changing the policy from color space to bit depth now is always better. Let say we have RGB and 10 bit YUV 4:2:0 - which would be better now?

**Comment by alatteri** [comment]
Hi Martin,
In the case of R10k or R12L, yuv444p16le would probably be the best choice.
Thanks.
Alan

**Comment by alatteri** [comment]
closing since this is working with yuv444p16le.
