### ISSUE TITLE
gpujpeg unsupported gpu architecture compute_30 Cuda SDK11

### ISSUE THREAD

**Issue by erichorwitz** [CESNET/UltraGrid#85]
/usr/local/cuda-11.0/bin/nvcc -Xcompiler -fPIC -Xcompiler  -O2 -I. -I/usr/local/cuda-11.0/include -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_35,code=compute_35  -I.  -c src/gpujpeg_huffman_gpu_encoder.cu -o src/gpujpeg_huffman_gpu_encoder.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_30'
Makefile:1305: recipe for target 'src/gpujpeg_huffman_gpu_encoder.cu.o' failed
make[1]: *** [src/gpujpeg_huffman_gpu_encoder.cu.o] Error 1
make[1]: Leaving directory '/home/localadmin/uv-build/sources/UltraGrid/gpujpeg'
Makefile:839: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

CUDA SDK 11 seems to only supports compute_52 and sm_52 as lowest version. 

in ./gpujpeg/configure

```
16854 case "$CUDA_COMPILER" in
16855         *nvcc*)
16856                 CUDA_COMPUTE_ARGS="-gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_35,code=compute_35"
16857                 ;;
16858         *clang*)
16859                 CUDA_COMPUTE_ARGS="--cuda-gpu-arch=sm_30 --cuda-gpu-arch=sm_35"
16860                 CUDA_FLAGS+=" --cuda-path=$CUDA_INSTALL_PATH"
16861                 ;;
16862         *)
16863                 as_fn_error $? "Unsupported cuda compiler $CUDA_COMPILER" "$LINENO" 5
16864                 ;;
16865 esac
```

**Comment by MartinPulec** [comment]
But you are not using current code, see [here](https://github.com/CESNET/GPUJPEG/blob/2842002b227be104d7ff69747da3fd5985f4683e/configure.ac#L131). Neither CMakeLists.txt contains the compute/sm specification explicitly.

**Comment by MartinPulec** [comment]
Also this is a wrong repository, thus closing that. If needed, please open the issue for [GPUJPEG](https://github.com/CESNET/GPUJPEG).

**Comment by erichorwitz** [comment]
Martin

This is the compile directive I used from the wiki. I pulled all the code yesterday so it should have been current.

Is there something wrong?


```
git -C Ultragrid pull 2> /dev/null || git clone https://github.com/CESNET/UltraGrid.git
cd ./UltraGrid/
git submodule update --init
cd ./gpujpeg/
./autogen.sh
make -j4
sudo make install
cd -
./autogen.sh --enable-rtsp-server --with-live555=/usr/local
make -j4
sudo make install
```

**Comment by MartinPulec** [comment]
I see, ok, thanks then it is

**Comment by erichorwitz** [comment]
I am building from master.

If i clone from GPUJPEG directly is there anything different for Ultragrid compile or will it find the libs automatically?

**Comment by MartinPulec** [comment]
There shouldn't be anything different whether compiled from a direct clone or UltraGrid submodule. The thing I was pointing to was that I've removed architecture specification in GPUJPEG master so it should not be the case there. But the submodule is updated occasionally so it might had not been reflected by UltraGrid submodule then. The submodule should, however, follow the master now.

**Comment by erichorwitz** [comment]
Thanks Martin!

I will not be able to test until Tuesday EST but I will be sure to let you know. 

I am actually having a similar problem with ffmpeg. I had to fork their code and modify the configure script to compile against cuda 11 SDK.

**Comment by MartinPulec** [comment]
Closing now - there have been multiple changes on that. Also there should not be any issue now (AFAIK).
