### ISSUE TITLE
Proprietary XIMEA Drivers

### ISSUE THREAD

**Issue by TechnologyClassroom** [CESNET/UltraGrid#91]
Why are the proprietary XIMEA drivers included?

This page says the license is proprietary: https://github.com/CESNET/UltraGrid/blob/4b465986ebc82265dcb0aec7b25f78b08ee32f11/package_specs/ultragrid-proprietary-drivers-ximea/ultragrid-proprietary-drivers-ximea.spec

This package seems to include them.  https://github.com/CESNET/UltraGrid/blob/4b465986ebc82265dcb0aec7b25f78b08ee32f11/package_specs/ultragrid-proprietary-drivers-ximea/debian.tar.gz

**Comment by xrucka** [comment]
Hello,

they are not included. What you reffer to is a rpm (.spec) and deb (debian.tar.gz) package build description that I had to write to include the drivers in our internal builds. The reason the build description is public is simple - if one wants to do a custom build with these drivers included, just combines in the proprietary sources acquired through a normal download procedure on ximea websited with the build description and launches the build system.

If you inspect the files you reffer to, you'll find they contain no source code at all.
