### ISSUE TITLE
REQ: NDI Audio as source and destination.. & Missing MAC dependancy

### ISSUE THREAD

**Issue by thpryrchn** [CESNET/UltraGrid#94]
I have compiled with NDI support on High sierra, and I don't seem to have the ability to set the audio source, or destination to NDI. Am I missing something?

PS. There is a dependency that should be added for MAC compiling!!! It would have saved me tons of time... 
`brew install ossp-uuid`

**Comment by MartinPulec** [comment]
Hi,
thanks for reporting, can I ask you for some further information? How do you run the sender/receiver? Intended use is:

    uv -t ndi -s embedded <receiver>
    uv -d ndi -s embedded

If the above doesn't work, do you have any details (error on startup/normal run but doesn't send/receiver audio).

As with the `ossp-uuid` - I've one mac with High Sirra installed and after removing ossp-uuid it compiles with NDI (although there are MacPorts, not Homebrew) - can you add more details on the error without (a message or so)? The thing is that I'd like to determine what is this actually a dependency for.

Thanks a lot!
Martin

**Comment by thpryrchn** [comment]
Ok, Embedded dose work!! Sweet!!! the `brew install ossp-uuid` is needed for ciniform codec to build correctly...

**Comment by MartinPulec** [comment]
> the `brew install ossp-uuid` is needed for ciniform codec to build correctly...

Thanks for the info - I'll add it to the wiki.
